app/app.php
stylesheets/_component.piano.scss
stylesheets/pulsar.scss
views/lexicon/index.html.twig
views/lexicon/modules.html.twig
views/lexicon/patterns.html.twig
views/lexicon/patterns/piano.html.twig

Documentation: https://jadu.gitbooks.io/pulsar/content/piano_list.html
Resolves #12 
Also fixes issue with Lexicon not loading module & pattern UIs

Implement piano list UIs from CXM

---

stylesheets/_component.forms.scss
views/pulsar/v2/helpers/form.html.twig

form.file() input has unwanted background colour and layout

---

stylesheets/_component.forms.scss
stylesheets/_config.theme.scss

5 disabled field bg colour

---

stylesheets/_mixin.mixins-to-organise.scss

Resolves #31
Also includes a fix for the box-shadow effect on focused form controls.

31 modal solid bg ie8

---

Gruntfile.js
package.json

Added to `default` and `watch` tasks.
Closes #38

Add bless task for IE stylesheets

---

stylesheets/_component.buttons.scss
views/lexicon/tabs/buttons_labels.html.twig

Also add examples to Lexicon
Closes #4

Add disabled state for naked buttons

---

tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/group-mixed-inputs.html
tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/group-mixed-inputs.html.twig

Add a test case for a reported issue with using both `form` and `html` macros within the `form.group` helper

---

stylesheets/_component.datatables.scss

Add disabled option to table rows.

---

.travis.yml
composer.json

For branch analysis and less spammy notifications

Remove coveralls.io integration in favour of codecov.io

---

stylesheets/_component.progress-lists.scss

Change all progress list '-of-type' selectors to '-child' ones instead.

---

package.json

Explicitly define datatables.net dependency

---

src/Jadu/Pulsar/Twig/Extension/ArrayExtension.php
src/Jadu/Pulsar/Twig/Extension/AttributeParserExtension.php
views/pulsar/v2/helpers/form.html.twig
views/pulsar/v2/helpers/html.html.twig

Requested by me, they're no longer required and break twig.js.
Closes #80

Remove default argument values from helpers

---

.travis.yml
composer.json

Reduced current build time from ~5min to about 1.5min
Addresses #83

Add caching rules to Travis to speed up builds

---

stylesheets/_component.piano.scss

Fixed issue where piano content panes don't scroll when content overflows. Also fixed IE8 cut off issue.

---

stylesheets/_component.dropdowns.scss
stylesheets/_config.theme.scss
views/lexicon/tabs/buttons_labels.html.twig
views/pulsar/v2/helpers/html.html.twig

Assign additional classes to dropdown button element

---

stylesheets/objects/_object.media.scss
stylesheets/pulsar.scss

Example showing both piano list items and block list using the media object:
Codepen: http://codepen.io/pulsar/pen/2cf3bf12d98f67d6e504432a55cb0348?editors=1100
Docs to follow
Closes #117

Add media object

---

stylesheets/_component.block-list.scss

Also update code style.
Closes #115

Remove block list hover effect from block list items that aren't links

---

tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/button_dropdown-parent-class.html
tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/button_dropdown-parent-class.html.twig
views/lexicon/tabs/buttons_labels.html.twig
views/pulsar/layouts/base.html.twig
views/pulsar/v2/helpers/html.html.twig

Added optional parent_class for button_dropdown helper.
Closes #132

132 add ability to pass classes to button dropdown helper wrapper

---

stylesheets/_component.toggle-switch.scss

Tweak font size and spacing of toggle switch icons for narrow viewports.

---

stylesheets/_component.tables.scss

Properly vertically align buttons when used within tables.

---

stylesheets/_component.flash.scss
stylesheets/_palette.base.scss

Added flash message background and text colour responsibility to the state colour palette
Closes #133

Improve contrast of info flash messages

---

stylesheets/_component.datatables.scss
stylesheets/_component.tables.scss

Move button alignment fix into correct object/partial.

---

stylesheets/_component.datatables.scss

Create 'fixed' table layout option for datatables

---

tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/checkbox_inline-bare-class.html
tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/checkbox_inline-bare-class.html.twig
tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/checkbox_inline-class.html
tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/checkbox_inline-class.html.twig
tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/choice-class.html
tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/choice-class.html.twig
tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/radio_inline-bare-class.html
tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/radio_inline-bare-class.html.twig
tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/radio_inline-class.html
tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/radio_inline-class.html.twig
views/pulsar/v2/helpers/form.html.twig

Bare inline radio/checkboxes now apply classes to their inputs

---

stylesheets/_component.flash.scss
stylesheets/_palette.base.scss

Flash messages in IE8 should use RGB

---

stylesheets/_component.remove-button.scss

Error only present when building on Jenkins

Stop remove button throwing sass error about missing btn--naked class

---

stylesheets/_structure.forms.scss

Increase vertical whitespace to align help block text.

---

stylesheets/_component.navigation.scss

Make primary navigation scrollable when it exceeds the viewport height.

---

js/index.js
js/main.js
package.json
stylesheets/_component.datatables.scss
stylesheets/_component.forms.scss
stylesheets/_component.panels.scss
stylesheets/_palette.base.scss
views/lexicon/tabs/datagrid.html.twig

Add select plugin to Pulsar's browserify bundle and update datatables markup example

Add datatables-select plugin

---

stylesheets/_component.choice.scss
views/lexicon/forms/choice.html.twig

Add ability for chocie blocks to hide their inputs

---

stylesheets/_component.panels.scss
views/lexicon/tabs/panels.html.twig

Add utility classes for centered and padded panels

---

stylesheets/_override.shame.scss
stylesheets/_structure.forms.scss

Reduce left padding by 10px on indented form groups.

---

stylesheets/_component.select2.scss

Select2 dropdown should no longer be hidden when select2 is used in a modal

---

stylesheets/_component.navigation.scss

Use consistent horizontal spacing between inline navigation tabs

---

stylesheets/_component.datatables.scss

Update datatable pagination styling

---

.gitattributes

Removed export-ignore for font-awesome css

---

stylesheets/_component.forms.scss
stylesheets/_override.shame.scss

Forms in modals have unwanted dulplicate margin

---

stylesheets/_component.tables.scss

Removed is-disabled styling from table-row__actions

---

stylesheets/_mixin.label-variant.scss

Also fixed indentation on this file
Fixes #268

Make label background and text colours immutable

---

stylesheets/_component.tooltips.scss
stylesheets/_config.variables.scss

Use a solid black background for tooltips in IE8

---

stylesheets/_component.forms.scss
stylesheets/_component.input-groups.scss
tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/date-append.html
tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/date-prepend.html
tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/text-append-button.html
tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/text-append-button.html.twig
tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/text-append-guidance.html
tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/text-prepend-button.html
tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/text-prepend-button.html.twig
tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/text-prepend-guidance.html
tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/text-prepend.html
views/lexicon/tabs/forms.html.twig
views/pulsar/v2/helpers/form.html.twig
views/pulsar/v2/helpers/util.html.twig

174 prepended appended inputs don’t respect width modifiers and aren't responsive

---

stylesheets/_component.forms.scss
stylesheets/_component.input-groups.scss

294 prepended appended inputs exceed width modifiers

---

stylesheets/_component.uploader.scss

Fix alignment issues in uploader

---

stylesheets/_palette.base.scss
stylesheets/_utility.sortable.scss

Closes #286 
(poor gif quality)

Change sortable action colour to yellow

---

stylesheets/_component.select2.scss

select2 height now matches other inputs

---

stylesheets/_component.button-groups.scss
stylesheets/_component.edit-button.scss
stylesheets/_component.input-groups.scss
stylesheets/_component.remove-button.scss
tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/text-append-button.html
tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/text-prepend-button.html
views/pulsar/v2/helpers/form.html.twig

Make prepended/appended buttons look more button'y

---

stylesheets/_mixin.mixins-to-organise.scss

Also adds support for `.has-success`, `.has-warning`, `.has-info` and `.has-changed`
Closes #324

Select2 elements are now correctly outlined with standard state classes

---

stylesheets/_utility.states.scss

Make state classes immutable

---

stylesheets/_component.buttons.scss
stylesheets/_component.panels.scss

Force box-shadow for all outlined button states.

---

stylesheets/_deprecated.styles.scss

One richer-list is still in use for CXM History UI. Will be phased out in near term.
/cc @jamesjacobs

Move deprecated richer list styles into deprecated stylesheet

---

tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/button-link.html
tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/edit_button-link.html
tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/label-removable-states.html
tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/label-removable.html
tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/remove_button-link.html
views/pulsar/v2/helpers/html.html.twig

Remove invalid type attribute from link buttons

---

stylesheets/_component.navigation.scss

Primary navigation should no longer be scrollable on touch devices

---

stylesheets/_structure.scaffolding.scss

Remove the black space at the bottom of the sign in page

---

package.json

Medium severity vuln found in moment@2.14.1, introduced via moment@2.14.1
- desc: Regular Expression Denial of Service
- info: https://snyk.io/vuln/npm:moment:20161019
Remediation options Upgrade to moment@2.15.2

Update moment lib due to newly found vulnerability

---

js/main.js
stylesheets/_utility.sortable.scss
views/lexicon/tables.html.twig
views/lexicon/tables/sortable.html.twig

Also add lexicon example.
Closes #421

Sortable tables now show and update their order sequence

---

stylesheets/_component.navigation.scss
views/pulsar/v2/helpers/nav.html.twig

This will allow continuum products to be linked together.
Closes #433

Add ability to use image instead of icon for primary navigation items

---

js/PulsarFormComponent.js

Colour picker will not update the value when the input is disabled

---

stylesheets/_component.forms.scss

Fix form with nesting issue within CMS legacy UIs

---

Gruntfile.js

Added autoprefixer to default, build and deploy tasks.

---

stylesheets/_component.forms.scss
stylesheets/_palette.base.scss

Increased contrast on help block text to meet AA

---

stylesheets/_component.tables.scss

Specifically the issue was a large width in the first column of tables in Utilities > Bulk Mail, Utilities > Locales, Events > Event Locations.
[CMS Ticket](https://jadultd.atlassian.net/browse/CMS-4183)

CMS - Fix Actions Misaligned in Pulsar UIs

---

docs/_styleguides/state.md
stylesheets/_utility.states.scss

Need `text--primary` styles for an XFP UI

Add text state styles

---

docs/utility-classes.md
stylesheets/_deprecated.styles.scss
stylesheets/_utility.misc.scss
stylesheets/_utility.utilities.scss
stylesheets/pulsar.scss

Deprecates the older multiple instances in favour of a common class structure

Refine utility classes to `.u-` namespace

---

stylesheets/_layout.report.scss

Late addition to the previous cms-reporting merge request.

Change Muted Extend to Optional

---

js/HelpTextComponent.js
tests/js/web/HelpTextComponentTest.js

Fixes #511 
Tested in Edge-IE9, FF, safari and Chrome. Also tested with NVDA and JAWS.

Changed help text JS to use hide class rather than visibility-hidden

---

js/NavMainComponent.js
stylesheets/_component.navigation.scss

This commit checks the content of the label inside a Primary Nav Item and when it is too big changes the height and the padding to look similar to the other items.

Add Primary Nav Item Height Adjustment

---

js/FilterBarComponent.js
package.json

FilterBar should no longer init select2s with data-init=“false”

---

.travis.yml

Stop Snyk running on Travis

---

stylesheets/_component.choice.scss
stylesheets/_component.forms.scss
stylesheets/_component.input-groups.scss
stylesheets/_component.select2.scss
stylesheets/_component.toggle-switch.scss
stylesheets/_override.shame.scss
stylesheets/_structure.forms.scss

Covered all input examples in lexicon

Move 1% margin from form controls to the main controls container

---

docs/_form-helpers/toggle.md
views/lexicon/patterns/masterswitch/masterswitch-enabled.html.twig

Add toggle documentation, and an enabled lexicon example

---

stylesheets/_config.variables.scss

Fixes issue in CXM which obscured certain important information

Tooltips now appear over flash messages

---

js/NavMainComponent.js
tests/js/web/NavMainComponentTest.js

Added check for required params to `NavMainComponent`. Fixes #654 
Also fixed box-shadow issue (fixes #655):

Fixed window infinite loop and box shadow issues

---

stylesheets/_layout.tabs.scss

Fixed nav bar height issue

---

stylesheets/_component.navigation.scss

This is the fix for Ealing (SUP-15045 / SUP008057)

Remove Height 100% from nav-link

---

.gitignore

Untrack and ignore bundle.js for documentation

---

stylesheets/_component.module-permissions.scss

Addition of media queries for improved Module Permissions responsiveness. 
Tested it in CMS

[CMS-5117] Module row misalignment on admin roles

---

docs/utility-classes.md

Adds current state of utility classes to the documentation

Utility classes documentation

---

stylesheets/_component.forms.scss

Increased specificity of input group form controls

---

stylesheets/_component.forms.scss

Fix for radio inputs showing ticks when selected

---

stylesheets/_component.greeter.scss
stylesheets/_config.branding.scss

- Added brandmark and generic-brandmark to branding
- Changed greeter to reference the two newly created branding variables

Make greeter component more generic by changing brand images references

---

js/NavMainComponent.js
stylesheets/_component.datatables.scss
tests/js/web/NavMainComponentTest.js

Fixes a console log issue raised in https://jadultd.atlassian.net/browse/CMS-5669
| require changes to `pulsar.scss` | ✅ No |
| require changes to `gruntfile.js` | ✅ No |
| require changes to `package.json` (not including dev dependencies) | ✅ No |
| require changes to `base.html.twig` (or other core views like header/footer) | ✅ No |
| require new arguments to be passed to a js component | ✅ No |
| require markup changes to maintain functionality | ✅ No |

Make sure quaternary nav works with button links

---

stylesheets/_component.forms.scss

Fixes #915 
**Tested in:**
**Post fix:**

fixed choice float issue

---

js/libs/tooltip.js
stylesheets/_component.datatables.scss
stylesheets/_component.filterbar.scss
stylesheets/_component.forms.scss
stylesheets/_component.modals.scss
stylesheets/_component.navigation.scss
stylesheets/_component.pagination.scss
stylesheets/_component.piano.scss
stylesheets/_component.search.scss
stylesheets/_component.slider.scss
stylesheets/_component.tab-help.scss
stylesheets/_component.toggle-switch.scss
stylesheets/_component.toolbar.scss
stylesheets/_structure.scaffolding.scss

This branch contained various mobile improvements detailed below:
1. Modals are now larger on mobile (see screenshot1)
2. Platform specific appearance is now removed for form inputs and main search - mainly to remove the iOS inner shadow. (see screenshot 1)
3. Pagination number are hidden on mobile, previous and next are displayed. (see screenshot 2)
4. `.nav-inline` has been made 100% width.
5. `font-size` and `line-height` has been increased to match desktop. This avoids iOS zooming into the page when a form field gains focus. (see screenshot 1)
6. Sidebar help icon has been correctly aligned on mobile.  (see screenshot 3)
7. Removed blue background colour on selected piano item on mobile.  (see screenshot 4)
8. `slider` ui no longer aligns to the left on mobile.
9. Spacing on `toolbar` …

Various mobile improvements

---

stylesheets/_component.datatables.scss
stylesheets/_component.pagination.scss

Due to issues caused by inconsistent pagination across products.

Reverting earlier pagination changes

---

package-lock.json
package.json

https://app.snyk.io/vuln/SNYK-JS-JSTREE-72490

Update jsTree to address potential vulnerability

---

stylesheets/_utility.utilities.scss

Simple grouping of classes to reflect the new documentation page I'm adding for utility classes.

Tidy up and reorganisation of utilities stylesheet

---

package-lock.json
package.json

Include templateSelection fixes

Bump jadu/selectWoo to 1.1.1

---

views/pulsar/layouts/base.html.twig
views/pulsar/layouts/pulsar.html.twig

This change makes the main search form a search landmark.
closes #1137

Added role=“search” to main search form

---

views/lexicon/includes/notifications.html.twig
views/lexicon/patterns/reporting/building.html.twig
views/lexicon/patterns/reporting/report.html.twig
views/lexicon/tabs/buttons_labels.html.twig
views/lexicon/tabs/modals.html.twig

Update lexicon examples where deprecated tooltips are used to the new accessible tooltips.

Update lexicon tooltip examples with new tooltips

---

js/index.js
js/libs/modal.js

Modals no longer close on backdrop/body click.
Closes #1153

Prevent modals closing on body click

---

js/DropZone/DropZoneComponent.js
js/DropZone/DropZoneComponentUtils.js
stylesheets/_component.dropzone.scss
tests/js/web/DropZone/DropZoneComponentUtilsTest.js
views/lexicon/forms/dropzone.html.twig
views/pulsar/v2/helpers/html.html.twig

This changes includes the following:
1. browse files element changed from link to button with an improved accessible label
2. remove link changed to button with improved accessible label
Fixes #1162

Dropzone a11y improvements

---

stylesheets/_component.signin.scss

Restores expected visual presentation of checkboxes in Firefox

---

stylesheets/_component.forms.scss

Closes #1470 
**Before**
**After**

Stop select elements in iOS displaying blue text

---

.github/workflows/php.yml
js/FlashMessageComponent.js

Adds hidden text to the prototype markup used to render flash messages triggered by js.
Closes #1485

Add discernable text to the close button of javascript flash messages

---

.github/workflows/codeql.yml
.github/workflows/docs.yml
.github/workflows/js.yml
.github/workflows/php.yml

Github Actions were significantly out of date.

Fix JavaScript GitHub Actions workflow
