- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/tabs/tabs_list-fragment.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/tabs/tabs_list-fragment.html.twig
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/tabs/tabs_list-full-url.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/tabs/tabs_list-full-url.html.twig
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/tabs/tabs_list-relative-url.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/tabs/tabs_list-relative-url.html.twig
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/tabs/tabs_list-string.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/tabs/tabs_list-string.html.twig
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/tabs/tabs_list-template.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/tabs/tabs_list-template.html.twig
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/tabs/template.twig
- tests/unit/Jadu/Pulsar/Twig/Macro/MacroTest.php
- views/pulsar/v2/helpers/tabs.html.twig
Resolves #13 
Matches against the following criteria:
If `src` starts with `#`, `/` or `http` then it will be treated as a link, no content pane will be created by the `tabs.content()` helper.
Otherwise, `src` templates will be a parsed as usual.
> Allow full and partial URLs to be used as inline tab links

- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/tabs/tabs_list-fragment.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/tabs/tabs_list-full-url.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/tabs/tabs_list-relative-url.html
- views/pulsar/v2/helpers/tabs.html.twig
Modified tabs helper to no longer pass `data-toggle="tab"` when using full or partial URLs
> Tabs using links as the `src` should no longer throw a javascript error

- stylesheets/_component.forms.scss
> Fix vertical alignment of text for single-line form controls in IE8.

- stylesheets/_component.pagination.scss
- stylesheets/_palette.base.scss
- views/lexicon/index.html.twig
- views/lexicon/modules.html.twig
- views/lexicon/patterns.html.twig
- views/lexicon/tabs/pagination.html.twig
Fixes #45 by adding a new alias to the base colour palette, so disabled text can use `colour(text, disabled)` and be styled consistently.
Added a codepen example to the docs: https://jadu.gitbooks.io/pulsar/content/pagination.html
This PR also fixes an issue with the Lexicon's 'Components' links not working correctly.
> Disabled links in pagination should now be visually distinct

- stylesheets/_component.button-groups.scss
> Only use `inline-block` on button groups that aren't being used as form controls.

- stylesheets/_structure.forms.scss
> Add `word-wrap: break-word;` to prevent long form labels from overlapping their controls.

- src/Jadu/Pulsar/Twig/Extension/GetConstantExtension.php
- tests/unit/Jadu/Pulsar/Twig/Extension/GetConstantExtensionTest.php
Checks whether a constant is defined and returns the value, or null if it doesn't exist.
Addresses #6
> Add new get_constant extension to simplify constant checking within views

- stylesheets/_component.breadcrumb.scss
- stylesheets/_layout.tabs.scss
- stylesheets/_override.shame.scss
- views/pulsar/layouts/base.html.twig
Driven by the need for Continuum CMS and XFP to have breadcrumbs restored, especially in legacy UIs.
The breadcrumb styles being removed in this commit are the Pulsar 3's clone of CMS 1.10 styles and are good to be removed rather than deprecated.
`main-title` position has been tweaked to maintain a neat baseline, and also cope with the absence of `.breadcrumb` if it's not there.
Closes #101
> Update breadcrumb styles

- stylesheets/_component.toggle-switch.scss
Adds expected affordance that this element can be clicked on.
Closes #103
> Use cursor pointer when mousing over toggle-switch

- stylesheets/_component.status.scss
- stylesheets/pulsar.scss
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/status-title.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/status-title.html.twig
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/status-with-options.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/status-with-options.html.twig
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/status-with-state.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/status-with-state.html.twig
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/status.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/status.html.twig
- views/lexicon/tabs/buttons_labels.html.twig
- views/pulsar/v2/helpers/html.html.twig
Closes #109 
Documentation for gitbook:
----
Displays a small visual indication of state; helpful when used within table
cells or piano list keys to avoid the need for a user to check many items
individually to determine their state.
Status indicators should ideally have some text which indicates their context. For example, they could be sat next to a text label called 'Active', or within a table column entitled 'Online'. Try not to rely on this indicator alone.
<p data-height="200" data-theme-id="21222" data-slug-hash="mPrvqZ" data-default-tab="result" data-user="pulsar" class="codepen">See the Pen <a href="http://codepen.io/pulsar/pen/mPrvqZ/">docs - status indicators</a> by Pulsar (<a href="http://codepen.io/pulsar">@pulsar</a>) on <a href="http://codepen.io">CodePen</a>.</p>
<script …
> Add new status indicator component, helper and tests

- js/index.js
- stylesheets/pulsar.scss
This dependency has been removed from Pulsar, these includes need to be removed to prevent the build breaking, or 404s in the browser.
Closes #121
> Remove remaining query-toggles references

- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/status-placement.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/status-placement.html.twig
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/status-title.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/status-with-options.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/status-with-state.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/status.html
- views/lexicon/tabs/buttons_labels.html.twig
- views/pulsar/v2/helpers/html.html.twig
Defaults to top, but can be overridden.
Closes #112
> Turn html.status title attributes into a tooltip

- stylesheets/_component.button-groups.scss
- views/lexicon/tabs/buttons_labels.html.twig
- views/pulsar/layouts/base.html.twig
Main change is addition of this on L:35
```
@each $state, $state-color, $state-color-alt in $state-colors {
> .btn--#{$state}:not(:first-of-type):not(.btn--naked) {
border-left-color: darken(color($state), 10);
border-right-color: darken(color($state), 10);
}
}
```
Fixes #126
> Add state-specific border colours to button groups

- js/PulsarFormComponent.js
- stylesheets/_component.choice.scss
- stylesheets/_config.variables.scss
- stylesheets/pulsar.scss
- tests/js/PulsarFormComponentTest.js
- views/lexicon/tabs/forms.html.twig
Block styling is available for the choice helper, add the `choice--block` modifier class. Pass a standard [form width modifier](styleguide-forms.md) to the choice helper's `class` option to control the width of all options.
```
{{
form.choice({
'label': 'Blocky options',
'class': 'choice--block form__group--medium',
'options': [ ... ]
})
}}
```
<p data-height="180" data-theme-id="21222" data-slug-hash="XdzwME" data-default-tab="result" data-user="pulsar" class="codepen">See the Pen <a href="http://codepen.io/pulsar/pen/XdzwME/">XdzwME</a> by Pulsar (<a href="http://codepen.io/pulsar">@pulsar</a>) on <a href="http://codepen.io">CodePen</a>.</p>
<script async src="//assets.codepen.io/assets/embed/ei.js"></script>
Add `choice--block choice--block-inline` to lay the options out horizontally. …
> 139 choice block

- stylesheets/_component.input-groups.scss
> Improve appearence of appended and prepended inputs

- stylesheets/_component.datatables.scss
> Add z-index: -1; to prevent table-selection TH from hiding TD border.

- package.json
node-sass `3.5.2` (a dependency of grunt-sass) causes "segmentation fault 11" locally and on Jenkins/Travis.
Locking to `3.4.2` for now to prevent this error.
Closes #166
> Lock to a known working version of node-sass

- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/block_list-class.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/block_list-class.html.twig
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/block_list-div-header-footer.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/block_list-div-header-footer.html.twig
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/block_list-div.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/block_list-div.html.twig
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/block_list-footer.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/block_list-footer.html.twig
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/block_list-header.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/block_list-header.html.twig
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/block_list-link-header-footer.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/block_list-link-header-footer.html.twig
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/block_list-link.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/block_list-link.html.twig
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/block_list-ol.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/block_list-ol.html.twig
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/block_list.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/block_list.html.twig
- views/pulsar/v2/helpers/html.html.twig
```twig
{{
html.block_list({
'items': [
{'value': 'foo'},
{'value': 'bar'},
{'value': 'baz'}
]
})
}}
```
```twig
{{
html.block_list({
'type': 'link',
'items': [
{'label': 'foo', 'href': '#foo'},
{'label': 'bar', 'href': '#bar'},
{'label': 'baz', 'href': '#baz'}
]
})
}}
```
Option | Type   | Description
------ | ------ | --------------------------------------------------------------
class  | string | CSS classes, space separated
footer | string | String/Markup to display in the footer row
header | string | String/Markup to display in the header row
id     | string | A unique identifier, if required
items  | array  | An `options` hash which will added as attributes to the `div`, `li` or `a` element (defined by `type`)
type   | string | Markup scheme to use: `ul` (default), `ol`, `div` or …
> Block list helper

- stylesheets/_component.choice.scss
- views/lexicon/forms.html.twig
- views/lexicon/forms/choice.html.twig
- views/lexicon/forms/text.html.twig
Added some flex box goodness for modern browsers top stop choice block layouts looking too screwy when labels wrap to separate lines.
This PR addresses a single real-world issue we're resolving for Continuum CMS, a couple of other tickets have been created for related enhancements that will need more time to investigate.
* #176 has been added to test https://github.com/10up/flexibility as a suitable IE8 polyfill.
* #175 has been created to add the ability for choice blocks to hide their inputs
Closes #171
> Stop inline choice block layout breaking when a label wraps onto multiple lines

- package.json
- stylesheets/_component.block-list.scss
`.block-list--padded` doesn't exist, node-sass has been updated and now reports this (rightly) as an error condition
Fixes #187
> Update node-sass dependency and fix sass issue with block-list extends

- js/PulsarFormComponent.js
- tests/js/PulsarFormComponentTest.js
- views/lexicon/forms/choice.html.twig
Observe new behaviour when page refreshed:
Closes #192
> Choice block inputs with `selected` should have `is-selected` class applied on page load

- stylesheets/_component.toggle-switch.scss
> Stop toggle switch labels from inheriting state modified text colour

- stylesheets/_component.forms.scss
- views/lexicon/forms.html.twig
Add extra padding around element only when it's using a state variation so that the default help blocks don't get pushed down too far.
Closes #182
> Improve styling of file input state variations

- js/main.js
- stylesheets/_component.datatables.scss
- stylesheets/_component.tables.scss
Mostly caused by a `-1` z-index
> Fix odd datatables row highlight in chrome and restore functionality in firefox

- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/create-nonce.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/create-nonce.html.twig
- views/pulsar/v2/helpers/form.html.twig
Option  | Type   | Description
------- | ------ | -------------------------------------------------------------
nonce   | string | Random string used to prevent CSRF, adds a hidden `nonce` input after `<form>`
Closes #209
> Add ability for `form.create` to create a hidden input with the value of `options.nonce`

- stylesheets/_component.breadcrumb.scss
- stylesheets/_component.toolbar.scss
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/nav/breadcrumb-items.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/nav/breadcrumb-items.html.twig
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/nav/breadcrumb.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/nav/breadcrumb.html.twig
- views/lexicon/index.html.twig
- views/pulsar/layouts/base.html.twig
- views/pulsar/v2/helpers/nav.html.twig
A basic helper to render a list of breadcrumb links. A view should set the `breadcrumbs` object which will then be rendered by the base template.
```twig
{%
set breadcrumbs = [
{'label': 'foo', 'href': '#foo'},
{'label': 'bar', 'href': '#bar'},
{'label': 'baz', 'href': '#baz'}
]
%}
```
```html
<nav class="breadcrumb">
<a href="#foo">foo</a> /
<a href="#bar">bar</a> /
<a href="#baz">baz</a>
</nav>
```
> Add breadcrumb helper

- stylesheets/_component.labels.scss
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/label-removable.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/label-removable.html.twig
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/remove_button-input.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/remove_button-link.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/remove_button-placements.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/remove_button-submit.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/remove_button-target.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/remove_button.html
- views/lexicon/index.html.twig
- views/lexicon/tabs/buttons_labels.html.twig
- views/pulsar/v2/helpers/html.html.twig
```
{{
html.label({
label: 'default',
removable: true
})
}}
```
Normal remove buttons have a `target` attribute, for these we will assume—at this point—that whatever JS is wired up by the developer will simply reference the element being clicked. (the helper still outputs `data-action-target="this"`)
> Add `removable` option to `html.label` helper

- stylesheets/_structure.forms.scss
> Help blocks for form.select2 should have same spacing as regular selects

- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/countdown-format.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/countdown-format.html.twig
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/countdown.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/countdown.html.twig
- views/playground/countdown.html.twig
- views/pulsar/layouts/base.html.twig
- views/pulsar/v2/helpers/html.html.twig
Add a live countdown to a specific date/time. This is a basic implementation for the time being, speak to Pulsar team if you need extra functionality as per [http://hilios.github.io/jQuery.countdown/documentation.html](http://hilios.github.io/jQuery.countdown/documentation.html)
```twig
{{
html.countdown({
'final-date': '2020/01/01 12:34:00',
'format': '%ww %dd %Hh %Mm %S',
'label': 'Expires 01/01/2010 at 12:34pm'
})
}}
```
This will render a simple string which will start counting down. You can style this as you wish. You can provide your own `format` string to provide the most appropriate countdown (ie: there's no point having a countdown using weeks if the final date is only based a few hours away).
Option     | Type   | Description
---------- | ------ | …
> New countdown helper for jQuery.countdown plugin

- stylesheets/_component.flash.scss
- stylesheets/_component.navigation.scss
Fixed through use of existing ` $zindex-nav;` variable on the main navigation container.
Closes #234
> Stop flash messages appearing on top of navigation

- stylesheets/_component.tables.scss
- views/lexicon/tabs/datagrid.html.twig
Does not apply to datagrid pagination.
Closes #240
> Pagination component should be correctly aligned with its table

- stylesheets/_component.tables.scss
- stylesheets/_utility.utilities.scss
Keep supporting `.no-wrap`, no plans to deprecate that just yet
> Update no-wrap table class to support new .u- utility format

- stylesheets/_component.navigation.scss
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/tabs/tabs_list-disabled.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/tabs/tabs_list-disabled.html.twig
- views/pulsar/v2/helpers/tabs.html.twig
Example:
```
...
{
"id"    : "buttons",
"label" : "Buttons",
"src"   : tab_buttons,
"disabled": true
}
...
```
Closes #233
> Allow inline navigation links to be disabled

- js/PulsarUIComponent.js
- stylesheets/_component.datatables.scss
- stylesheets/_component.tables.scss
- tests/js/web/PulsarUIComponentTest.js
If your table has no results in the `tbody` then the table will show a generic message. This message can, and should, be customised to suit the content in question via the `data-empty-table` attribute.
```
<table class="table datatable" data-empty-table="There are currently no documents to display">
... 
</table>
```
Datatables allow selection of rows by default, this behaviour can be disabled through the `data-selection` attribute. This will hide the related elements in the UI.
```
<table class="table datatable" data-selection="false">
...   
</table>
```
> Make datatables automatically render 'no results' message

- stylesheets/_component.buttons.scss
- views/lexicon/tables.html.twig
Button background/label colours are tightly defined, to allow components to work with link colours without affecting buttons, judicious use of `!important` will allow us to make sure button colours are immutable.
Addresses #257
> Make button colours immutable

- views/pulsar/layouts/base.html.twig
This change is mainly a test to prove that there's no adverse effects with moving the main js bundle out of the `<head>`
Closes #277
> Move js bundle out of <head> in base template

- stylesheets/_component.toolbar.scss
Dropdowns in the toolbar now follow the same behaviour as the notifications container.
Addresses #305
> Make toolbar dropdowns fit screen width at smaller sizes

- stylesheets/objects/_object.media.scss
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/icon_colour.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/icon_colour.html.twig
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/media-icon-color.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/media-icon-color.html.twig
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/media-icon.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/media-icon.html.twig
- views/lexicon/index.html.twig
- views/lexicon/tabs/media.html.twig
- views/pulsar/v2/helpers/html.html.twig
> Allow media helper to accept an icon as an alternative to an image

- .gitignore
- fonts/_config.fonts.scss
- makefile
- stylesheets/pulsar.scss
Jadu developers can now use Proxima Nova in the Lexicon. For licensing reasons, non Jadu developers will not be able to do this unless they add their own licensed files.
Check out both the `pulsar` and `pulsar-fonts` repos (pulsar fonts available on Jadu's GitLab instance) to the same directory
eg: `localhost/pulsar` `localhost/pulsar-fonts`
In the pulsar repo, run `make`. This will copy the required pulsar fonts files from `pulsar-fonts/src` to `pulsar/fonts` as well as setting the existing empty `pulsar/fonts/_config.fonts.scss` to not track changes in git to precent accidental comitting of this file.
The lexicon should now be displayed with Proxima Nova 🙌
> Allow local use of Proxima Nova in Pulsar and the Lexicon

- stylesheets/_component.toolbar.scss
- views/lexicon/includes/notifications.html.twig
- views/pulsar/layouts/base.html.twig
Observed behaviour:
After changes:
> Fix issue where toolbar dropdowns were incorrectly positioned

- js/libs/popover.js
- js/libs/tooltip.js
- views/lexicon/tabs/tooltips.html.twig
Have changed bootstrap's tooltip plugin to use `tooltips` instead of `tooltip`, this seemed to be a far easier change than hosting our own build of jQueryUI, which we may have to do at some point, but is a little more complicated than I have time for right now.
Also updated Lexicon page to fix the issue with buttons shifting position.
Fixes #329
> jQueryUI’s tooltips should no longer override existing tooltip plugin

- stylesheets/_component.button-groups.scss
Resolves #316 
Bug was introduced with the commit 4faedf2e which made the default borders be of a higher specificity than those with state classes.
> Fix button group border colours when state classes are used.

- app/app.php
- app/test.php
- tests/css/DiffTest.php
This resolves an issue caused a change in Twig 1.25 preventing pages from being loaded.
Closes #335
> Remove relative paths from Twig loaders

- README.md
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/toggle_switch-class.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/toggle_switch-class.html.twig
- views/pulsar/v2/helpers/form.html.twig
Resolves an issue introduced recently in 0259c65 which overrode existing `class` options and broke CMS masterswitch UIs. Added test cases to avoid this happening again.
> Toggle switch helper should add class param to its container

- Gruntfile.js
- hooks/pre-commit
PHPUnit tests take ~1 minute to run and slow down regular development, these should be run by the developer as part of their own testing process before pushing to GitHub.
The pre-commit hook was also added before we had Travis running build jobs.
> Remove pre-commit git hook and grunt tasks

- stylesheets/_component.buttons.scss
- stylesheets/_utility.utilities.scss
- stylesheets/objects/_object.box.scss
* Make `.bottomless` utility class immutable
* Fix disabled styling on naked buttons (spotted with wraith)
* Add `.box--naked` variant to allow a visually unboxed area to sit underneath a boxed area and maintain the same padding
e.g. here, the checkboxes on the white bg are with a `.box--naked` to match alignment with those within the grey box above.
> Changes required for CMS Maintenance UI

- stylesheets/_component.forms.scss
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/choice-optimize-many-guidance-container.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/choice-optimize-many-guidance.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/choice-optimize-many.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/choice-optimize-multiple.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/choice-optimize.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/select2-bare.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/select2-error.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/select2-guidance-container.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/select2-guidance.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/select2-multiple.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/select2.html
- views/pulsar/v2/helpers/elem.html.twig
Rather than setting a border on all inputs, they're now only set on text, textarea, password and select/select2 leaving the browser to style checkboxes and radios as they see fit.
Closes #370
> Restore outline to checkbox and radio inputs in iOS

- composer.json
The `symfony/yaml` dependency is only used during the `grunt wraith-update` task to write to `wraith.yml` and so isn't used in production.
Moving this to a development dependency should stop CMS and CXM throwing a warning about mismatched versions.
* Removing `/vendor` and running `composer install` passed fine
```
- Installing symfony/yaml (v2.6.13)
Loading from cache
```
* Running `composer update` on current state of `develop` worked fine
```
~/Localhost/1-12 on develop*
$ composer update
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
Loading composer repositories with package information
Updating dependencies (including require-dev)
- Updating jadu/pulsar dev-yaml (ea18b57 => 6a28238)
Checking out …
```
> Move yaml dependency to require-dev

- package.json
Stops us hitting the newly implemented unauthed limits on snyk.io, it will still run (authed) on Travis during builds.
Closes #364
> Stop snyk from running on `npm test`

- stylesheets/_override.shame.scss
Removed a possible CXM specific override (circa July 2015) which, if still required, should perhaps be a modifier class instead of default behaviour? @jamesjacobs could you please review and see if this will break any CXM UI?
Before:
After:
Closes #261
> Form group small should no longer constrain help text to the input width

- stylesheets/_component.flash.scss
- stylesheets/_component.navigation.scss
> Flash message should no longer have 1px offset in some browsers

- makefile
* Make no longer checks for existing versions, we trust in the package managers to deal with that for us.
* Removed xcode command line tools, as make doesn’t even exist without these (and OSX promts for their installation as soon as you run make anyway)
* Added vagrant installation
* Added virtualbox installation
* Fixed path to homebrew installation script, stopped it prompting for y/n confirmation
* Stop brew installs breaking when the package already exists
* Added ImageMagick installation
* Added Wraith installation
Also created a wiki page to track known make related issues: https://github.com/jadu/pulsar/wiki/Make
> Add Wraith dependencies to makefile and tidy things up somewhat

- stylesheets/_deprecated.styles.scss
An old `$state-colors` map was in the deprecated styles file, and was preventing the changes to the base palette from being included.
Closes #383
> Restore expected colours to btn—white

- stylesheets/_component.footer.scss
- stylesheets/_component.navigation.scss
- stylesheets/_config.branding.scss
- stylesheets/_config.variables.scss
- stylesheets/_layout.tabs.scss
* Removes legacy navigation variable values
* Adds new nav width variable value and uses that whevever we’re calculating things for the layout  based on the nav width
> Primary nav no longer shows incorrect 1px offset

- stylesheets/_structure.scaffolding.scss
Have had a look at this change on Lexicon & CMS and can't see anything has broken
> Stop some CMS UIs from being non-scrollable

- Gruntfile.js
- stylesheets/_component.greeter.scss
Continuum CMS will now show version numbers in the footer, previously this was reserved for Jadu branding but never used.
Also updates indentation to 4 spaces.
> Add new styles to greeter footer for CMS version numbers

- Gruntfile.js
This should fix the issue where css output within `/dist` wasn’t compressed.
Closes #399
> Use correct outputStyle option name in Grunt Sass task

- js/main.js
- stylesheets/_mixin.mixins-to-organise.scss
- stylesheets/_utility.sortable.scss
- views/playground/sortable/tab.html.twig
Just needs the `.is-sortable` class adding to a table, probably not advisable to use this in conjunction with datatables.
Will be used in Continuum CMS to add sortability to things like download files lists.
Had to qualify the is sortable class into `div.is-sortable` and `.table.is-sortable` so as not to break backwards compatibility with existing sortable items, happy to discuss better ways of doing this.
```
<table class="table is-sortable">
```
> Table rows can now be sorted if the table has the is-sortable class

- stylesheets/_component.tab-help.scss
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/toggle_switch-class.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/toggle_switch-error.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/toggle_switch-guidance-container.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/toggle_switch-guidance.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/toggle_switch.html
- views/pulsar/v2/helpers/form.html.twig
Revert change which removed the `for` attribute from the toggle control and meant it could no longer be clicked.
> Clicking toggle control now toggles the element again

- stylesheets/_component.signin.scss
Following a discussion with a user with mild epilepsy, who reported that he had to look away whenever signing into Continuum CMS.
Closes #406
> Remove the ‘flyout’ animation from Continuum Sign-in

- stylesheets/_component.forms.scss
- tests/css/visual-regression-layout.html.twig
> Make select2 elements have same disabled styling as regular selects

- stylesheets/_structure.scaffolding.scss
This issue was encountered in Android 6.0.1.
closes #456
Tested on Samsung Galaxy, iPad and OnePlus3.
> Fix Android Right Extra Space

- views/pulsar/layouts/base.html.twig
- views/pulsar/v2/helpers/html.html.twig
- views/pulsar/v2/helpers/nav.html.twig
Did a quick pass of Continuum CMS through the HTML validator and fixed a couple of minor issues.
> Fix HTML validation issues

- src/Jadu/Pulsar/Twig.js/Extension/AttributeParserExtension.js
- src/Jadu/Pulsar/Twig/Extension/AttributeParserExtension.php
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/link-disabled.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/link-disabled.html.twig
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/tabs/tabs_list-disabled.html
- views/pulsar/v2/helpers/html.html.twig
----
Passing the `disabled` option to the `html.link` helper will no longer output the `disabled` boolean attribute in the markup which was throwing W3C validation errors.
This has required changes to the AttributeParserExtension (both PHP and JS) to allow us to pass an optional `tag` to the parser letting us modify the parsers output on a tag by tag basis.
Given this example:
```
html.link({
'label': 'foo',
'href': '#',
'disabled': true
})
```
We need the `disabled` option to be passed to the parser in order for the `aria-disabled="true"` and `class="is-disabled"`attributes to be created, so we can't simply add `excludes('disabled')`, but we **do not** want the plain `disabled` attribute to be present on links, but we **do** want it on other elements like form inputs.
Passing the tag …
> Stop disabled link helper from generating invalid HTML

- stylesheets/_component.select2.scss
- stylesheets/pulsar.scss
- views/lexicon/forms/select2.html.twig
I've copied the select2 stylesheet from `/libs` into our own `_component.select2.scss` so that we can modify them without constantly having to override them.
Caret is the same as regular select & select2 single elements.
Closes #478
> Add caret to select2 multiple dropdown elements

- stylesheets/_component.piano.scss
This is a fix for ticket: [https://jadultd.atlassian.net/browse/PER-149](https://jadultd.atlassian.net/browse/PER-149)
Makes the table inside Utilities>Integrations>Perceptive Content>Views full width in any browser IE8 up.
> CMS - Change Perceptive Content>Views>Table Full Width

- stylesheets/_component.piano.scss
Fixed a typo in class name and added missing class. This is part of the PER-149 ticket of CMS.
> CMS - Fix Typo and Missing Class

- makefile
- stylesheets/_component.forms.scss
Improves the appearance of bare `checkbox_inline` elements within the `help-block`
Before:
After:
> Remove extra padding when using a control label within a help block

- stylesheets/_component.modals.scss
Close button aligned correctly.
Fixes #496
> Close button alignment fix for chrome/safari in old OSX.

- stylesheets/_component.select2.scss
Issue down to the way IE handles visibility on parents. Seems you can't set a parent to be hidden and a child to be visible.
Fixed by 'hiding' the original X character by setting it to be the same colour as the background and stopping it from becoming visible again through hover.
Tested in IE11 and IE9 (My IE10 VM isn't working at the moment)
Closes #505
> Restore remove icons for Select2 elements in IE

- stylesheets/_component.buttons.scss
Change outline buttons to use border instead of box-shadow. Various padding values were tweaked to make sure button dimensions remained unchanged.
Wraith tests display no differences.
IE11
IE9
Closes #489
> Improve outline button rendering in IE

- js/MasterSwitchComponent.js
- tests/js/web/MasterSwitchComponentTest.js
- views/lexicon/patterns/masterswitch.html.twig
This allows a view to keep certain element disabled after the master switch has been enabled, such as integrations which need credentials supplying before other fields are enabled.
It's completely backwards compatible and doesn't require any changes to masterswitch components in the wild.
Closes #477
> Don't enable elements in the masterswitch that were already disabled within the view

- stylesheets/_structure.scaffolding.scss
Need padding instead of margin because of the way `.container` uses 100% height.
**Before:**
**After:**
> Fix issue where content longer than the viewport would be cut off by the footer

- stylesheets/_component.footer.scss
- stylesheets/_layout.tabs.scss
> 476 Broken footer and mobile menu styles in IE10/9

- stylesheets/_layout.tabs.scss
Fixed by removing footer height from `.inner-wrapper` height.
Tested in:
Fixes #498
> Fix unnecessary scrolling

- makefile
The current build process attempts to create a directory called `fonts` that already exists in the repo, this directory currently contains 1 empty file `_config.fonts.scss`, adding the `-p` / `--parents` flag to the `mkdir` command in the makefile will prevent the error from killing the process if the `fonts` directory already exists.
> add --parents flag to mkdir to prevent makefile failing

- Gruntfile.js
- package.json
Looks like we are at the bottom of the `jstree` issues (although not specific to jstree, that was just a symptom). The reason we were getting different results is the the difference in npm versions we are running. Version 3 of npm was not pulling down jstree's deps which meant it was using our top-level version of jquery (which is what we want) however for people that have upgraded from 3 to 4 and perform a npm update or clean install, npm installs jstree's version of jquery which was the problem.
The fix is to use a browserify transform called aliasify, which will rewrite jstree's require call to ensure it uses our top-level version of jquery. This will essentially restore the dependency structure to the npm@v3 environments.
> fix npm v3 & v4 issues to ensure 1 instance of jquery is being used

- stylesheets/_component.forms.scss
- views/lexicon/forms/text.html.twig
Expanded form__control styles to cover common HTML5 input types.
Note: additional enhancements could be made to cover `type="color"` and `type="range"` in the future and haven't been included in this ticket.
Fixes #527
> 527_html5-input-styles

- js/DisableUiComponent.js
- js/index.js
- js/main.js
- stylesheets/_component.masterswitch.scss
- stylesheets/_utility.utilities.scss
- tests/js/web/DisableUiComponentTest.js
Allows you to disable parts of a UI by adding the data-disable-ui="true" data attribute.
Form elements are disabled, links can not be clicked and a faded overlay is added.
> Disabled ui component

- stylesheets/_structure.forms.scss
Raised by @rcwsr, inline form inputs weren't aligning correctly.
Observed in Chrome.
**Before**
**After**
> Make inline form inputs align correctly

- package.json
This bug was identified when building Pulsar in the Jadu CMS, the original work (by me) had aliased jQuery require statements to the jQuery dependency installed by NPM. When Pulsar is installed by composer and bundled in the CMS, node_modules are not installed. This meant it was looking for a dependency that did not exist. I've fixed this by aliasing the jQuery dependency installed via Bower, which _is_ copied across when installed.
> alias jQuery version in libs folder for CMS installs

- docs/_form-helpers/select.md
- docs/_form-helpers/select2.md
- docs/assets/code_examples/form_helpers/html/select-optgroup
- docs/assets/code_examples/form_helpers/html/select2-optgroup
- docs/assets/code_examples/form_helpers/twig/select-optgroup
- docs/assets/code_examples/form_helpers/twig/select2-optgroup
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/select-optgroup.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/select-optgroup.html.twig
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/select2-optgroup.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/select2-optgroup.html.twig
- views/lexicon/forms/select.html.twig
- views/lexicon/forms/select2.html.twig
- views/pulsar/v2/helpers/elem.html.twig
Allows select options to be grouped within `<optgroup>`.
Maintains backwards compatibility with other option syntaxes.
Example:
```
{{
form.select2({
'label': 'Select with optgroups',
'options':
[
{
'label': 'optgroup one',
'options': [
{
'label': 'alpha',
'value': 'val-alpha'
},
{
'label': 'bravo',
'value': 'val-bravo'
}
]
},
{
'label': 'optgroup two',
'options': [
{
'label': 'charlie',
'value': 'val-charlie'
},
{
'label': 'delta',
'value': 'val-delta'
}
]
}
]
})
}}
```
Closes #543
> Add optgroup support to select helpers

- docs/_form-helpers/select2.md
- js/PulsarFormComponent.js
- views/lexicon/forms/select2.html.twig
- views/pulsar/v2/helpers/elem.html.twig
Example:
```twig
{{
form.select2({
'label': 'Pick a colour',
'id': 'foo',
'data-init': 'false',
...
```
> Add data attribute to prevent select2s from being automatically initialised

- stylesheets/_component.toggle-switch.scss
Mainly to allow easy keyboard accessibility.
Closes #573
> Add a highlight effect around toggle switches when they’re focused

- stylesheets/_structure.grid.scss
Small change, noticed that the base grid columns styles were repeated for each `g-col` instead of combining selectors.
**Hunger-games/develop**
```
┌──────────────┬─────────┐
│ Size         │ 532.1KB │
├──────────────┼─────────┤
│ Rules        │ 3706    │
├──────────────┼─────────┤
│ Selectors    │ 6871    │
├──────────────┼─────────┤
│ Declarations │ 7722    │
└──────────────┴─────────┘
```
**This branch**
```
┌──────────────┬─────────┐
│ Size         │ 530.1KB │
├──────────────┼─────────┤
│ Rules        │ 3695    │
├──────────────┼─────────┤
│ Selectors    │ 6871    │
├──────────────┼─────────┤
│ Declarations │ 7652    │
└──────────────┴─────────┘
```
Tested change in lexicon.
> Replaced repeated column base styles with placeholder extend

- stylesheets/_layout.tabs.scss
Spotted some unneeded styles around open nav / open help and `inner-wrapper`
*hunger-games/develop*
```
┌──────────────┬─────────┐
│ Size         │ 530.1KB │
├──────────────┼─────────┤
│ Rules        │ 3695    │
├──────────────┼─────────┤
│ Selectors    │ 6871    │
├──────────────┼─────────┤
│ Declarations │ 7652    │
└──────────────┴─────────┘
```
*This branch*
```
┌──────────────┬─────────┐
│ Size         │ 529.1KB │
├──────────────┼─────────┤
│ Rules        │ 3693    │
├──────────────┼─────────┤
│ Selectors    │ 6869    │
├──────────────┼─────────┤
│ Declarations │ 7636    │
└──────────────┴─────────┘
```
> Removed unneeded styles for open nav/open help and inner-wrapper

- stylesheets/_component.panels.scss
Used `@extend` to remove some duplicate declarations. Also moved `.form_group .panels` outside of the `@each` to prevent 7 duplicate blocks.
**hunger-games/develop**
```
┌──────────────┬─────────┐
│ Size         │ 530.1KB │
├──────────────┼─────────┤
│ Rules        │ 3695    │
├──────────────┼─────────┤
│ Selectors    │ 6871    │
├──────────────┼─────────┤
│ Declarations │ 7652    │
└──────────────┴─────────┘
```
**This branch**
```
┌──────────────┬─────────┐
│ Size         │ 529.2KB │
├──────────────┼─────────┤
│ Rules        │ 3680    │
├──────────────┼─────────┤
│ Selectors    │ 6856    │
├──────────────┼─────────┤
│ Declarations │ 7637    │
└──────────────┴─────────┘
```
> Panel optimisation

- js/NavMainComponent.js
- stylesheets/_component.buttons.scss
- stylesheets/_component.navigation.scss
- tests/js/web/NavMainComponentTest.js
Fixes issue where `is-active` was not removed from a closed secondary navigation list meaning its links were still focusable (and therefore you could navigate to them using the keyboard) when the menu was closed.
Fixes #575
> 575_secondary-nav-links-focus

- js/PulsarUIComponent.js
- stylesheets/_component.datatables.scss
- views/lexicon/tables.html.twig
- views/lexicon/tables/tablex.html.twig
Add `.table--horizontal` to a datatable to switch the responsive mode from 'collapse' to 'scroll'.
There's a separate datatable loader for this case which wraps the `<table>` element with the `table-container` div in a different DOM position than regular tables to maintain the position of the datatable header and pagination when scrolling.
```
<table class="table datatable table--horizontal table--full"> ... </table>
```
> Add table—horizontal support to datatables

- js/DisableUiComponent.js
- js/MasterSwitchComponent.js
- js/main.js
- tests/js/web/DisableUiComponentTest.js
- tests/js/web/MasterSwitchComponentTest.js
This allows us to use a common method of disabling different interactive elements within Puslar.
* Creates new `enable()` and `disable()` methods in DisableUIComponent
* Refactors `MasterSwitchComponent` to use the new methods
* Fixes an issue where the `switchOn/Off` methods were being called on both `click` and `change`
* Removes some tests from `MasterSwitchComponentTest` and assumes they methods called are (or will be) tested within `DisabledUIComponentTest`
Addresses #525
> Masterswitch now uses DisableUIComponent to disable the masterswitch contents

- .jshintrc
- js/DropZone/DropZoneBrowseNodeFactory.js
- js/DropZone/DropZoneBrowseNodeManager.js
- js/DropZone/DropZoneComponent.js
- js/DropZone/DropZoneComponentFactory.js
- js/DropZone/DropZoneInstanceManager.js
- tests/js/web/DropZoneBrowseNodeFactoryTest.js
- tests/js/web/DropZoneBrowseNodeManagerTest.js
- tests/js/web/DropZoneComponentTest.js
- tests/js/web/DropZoneInstanceManagerTest.js
An improvement to the DropZone API to allow toggling of the "Browse Files" functionality.
> Drag & Drop disable browse files

- stylesheets/_component.select2.scss
- stylesheets/_structure.grid.scss
The recent changes to `form__control` (it now uses the grid by default) resulted in select2 widths being miscalculated. This is down to select2 grabbing the width, which is a percentage and applying the same value as pixels.
As a fix, `.select2-container` now also uses the grid to ensure proper width at various vp widths. As select2 sets an inline width, I've added an option to the grid `span` mixin for adding `!important` to grid span widths (currently only used to fix the select2 issue).
Fixes #599
> 599 select2 elements have wrong default width

- stylesheets/_component.forms.scss
This prevents an issue where textareas can be expanded to break the containing layout.
The width of textareas should be defined by the documented form width modifiers and grid classes.
Closes #609
> Restrict textarea resizing to vertical axis only

- js/DropZone/DropZoneComponent.js
- js/DropZone/DropZoneInstanceManager.js
- tests/js/web/DropZoneComponentTest.js
- tests/js/web/DropZoneInstanceManagerTest.js
An issue has been identified in CXM where the DropZoneComponent is attaching events to an input node and implementing the File API, this is breaking on ie9 which does not support it.
The fix has added a condition to the DropZoneComponent which will avoid attaching any events to file input nodes if the DropZone supported option is false
> Prevent DropZone adding events to inputs in ie9

- docs/_form-helpers/select.md
- docs/_form-helpers/select2.md
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/select-append-prepend.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/select-append-prepend.html.twig
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/select-append.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/select-append.html.twig
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/select-prepend.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/select-prepend.html.twig
- views/lexicon/forms.html.twig
- views/lexicon/forms/select.html.twig
- views/lexicon/forms/select2.html.twig
- views/pulsar/v2/helpers/form.html.twig
Adds the same functionality as other form helpers.
Option       | Type    | Description
------------ | ------- | --------------------------------------------------------
append       | string  | Text or markup to include after the input element
append_type  | string  | Use only when appending a button. `button` is the only valid value
prepend      | string  | Text or markup to include before the input element
prepend_type | string  | Use only when prepending a button. `button`is the only valid value
```
{{
form.select({
'label': 'Appended',
'append': '.00',
'options': {
'foo': 'bar',
'bar': 'baz'
}
})
}}
```
Closes #636
> Add append/prepent support for select/select2 helpers

- js/FilterBarComponent.js
- tests/js/web/FilterBarComponentTest.js
**Problem**
Console error when trying to call the `select2.destroy()` method on a select2 that uses `data-init="false"
**Solution**
Use `.select2-hidden-accessible` which is added by select2 instead of our `.js-select2`, which we can't rely on to be honest about whether the select2 has been properly initialised.
> Fix console error when closing filterbar filter containing uninitialised select2

- stylesheets/_component.forms.scss
Prior to this fix input groups default to a fixed width and used the legacy `form__group` width modifiers. See issue #649.
Now they default to the new grid and are able to use the new grid classes.
Fixed #649
> input-group support for new grid sizes

- stylesheets/_component.forms.scss
Fixed the width issue in FF and IE (along with the bg colour issue).
Unfortunately due to the nested MQ generated by using the `col-span` mixin [here](https://github.com/jadu/pulsar/blob/662_checkbox-issues/stylesheets/_component.forms.scss#L332) when already inside [this MQ](https://github.com/jadu/pulsar/blob/662_checkbox-issues/stylesheets/_component.forms.scss#L307) the only option was to use a `not(.checkbox)` [here](https://github.com/jadu/pulsar/blob/662_checkbox-issues/stylesheets/_component.forms.scss#L331).
Previously this was generating this CSS
```
@media screen and (min-width: 600px) and (min-width: 480px) {
.control__label + .controls > .form__control {
width: 100%; } }
```
Which was more specific (by 1 MQ) than the width overrides (now removed).
Example of FF fix:
The …
> Fixed checkbox bg and width issue in FF and IE

- stylesheets/_structure.type.scss
- views/lexicon/tabs/message.html.twig
Issue was seen in Chrome and Firefox.
Closes #665
> Remove double underline on abbreviations

- stylesheets/_component.forms.scss
- stylesheets/_layout.sidebar.scss
- stylesheets/_layout.tabs.scss
- stylesheets/_structure.grid.scss
- views/lexicon/patterns/masterswitch/masterswitch-enabled.html.twig
> Fixed form actions misalignment

- docs/_components/card.md
- docs/_sass/_base.scss
- docs/assets/code_examples/html_helpers/html/card
- docs/assets/code_examples/html_helpers/html/card-body
- docs/assets/code_examples/html_helpers/html/card-header-footer
- docs/assets/code_examples/html_helpers/html/card-title-links
- stylesheets/_component.cards.scss
- stylesheets/pulsar.scss
- views/lexicon/index.html.twig
- views/lexicon/tabs/cards.html.twig
Cards are a flexible container for standout content with a range of configurable options for headers and footers, images and calls to action.
Cards can be sized and arranged using the common grid classes and respond well at small screen widths.
```
<div class="card">
<div class="card__body">
<h3 class="card__title">Card Title</h3>
<p>This is the card body, it should be helpful and descriptive.</p>
<a href="#cta" class="btn btn--primary">Call to Action</a>
</div>
</div>
```
Detailed examples in [card.md](https://github.com/jadu/pulsar/pull/690/files#diff-a5aff9c6f591a7ec91cfa32c67e27e96), helper will follow as a separate ticket once any issues here have been sweated out.
Closes #687
> Add card component and documentation

- package.json
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/button-xss.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/button-xss.html.twig
- views/pulsar/v2/helpers/html.html.twig
Restrict the allowable HTML elements within a `<button>` to the common phrasing tags we're likely to use.
> Whitelist specific phrasing tags for the html.button helper

- docs/_components/datatable.md
Very simple and small change. The correct syntax is
`data-select="false"`
> Correct Datatable Selection Option Wording in Docs

- stylesheets/_component.datatables.scss
An update of the datatables package caused a change in the markup of the dt-buttons. It used to be links now it is buttons. This is the reason of those new styles.
> [CMS-5087] Button issue on Pulsar's data table

- stylesheets/_component.select2.scss
**Safari**
**Chrome**
**Firefox**
**IE9**
**IE10**
**IE11**
Closes #702
> Add a box shadow to the select2 dropdown to offset against the background UI

- stylesheets/_component.forms.scss
The descendent selector was breaking legend styling in stuations where fieldsets were contained in another element like a `<section>`.
Fixes #712
> Make sure legends are consistently styled with underline

- js/NavMainComponent.js
This fixes an odd edge case identified in XFP where items unhidden through `show()` were being assigned `inline-block` rather than `list-type`.
To resolve this we now explicitly set that as the inline style rather than use `show()`.
Fixes #719
> Make sure unhidden primary nav items don’t use inline-block

- stylesheets/_component.flash.scss
- stylesheets/_component.panels.scss
- stylesheets/_palette.base.scss
- stylesheets/_palette.projector.scss
Previously flash messages had different colours to states colours and therefore didn't match elements such as panels - see #727.
Flash messages now use state colours. Also I noticed flash message and panels were outputting some unneeded CSS for a handful of states that weren't applicable to them, these have now been filtered out from the respective loops. Therefore: 
- `panel--base`
- `panel--white`
- `panel--new`
No longer exist. These don't seem to have been used anywhere and were visually broken. Suspect these were created by mistake and as a by-product of adding `base`, `white` and `new` to `$state-colors`. Note the colours have not been removed from `$state-colors` as they are used elsewhere.
I've also removed the old flash colours form the palettes.
New colours (All meet AA due to …
> Flash messages now use state colours

- stylesheets/_component.progress-lists.scss
Previously progress lists were not responsive. See #745
They are now 🎉
> Responsive progress lists 📱

- Gruntfile.js
- js/lexicon/lexicon-index.js
- stylesheets/_component.metadata.scss
- views/lexicon/tabs/colours.html.twig
- views/lexicon/tabs/metadata.html.twig
Metadata list now responds correctly at smaller VP widths. Removed unused bordered variation.
fixes #747
> Responsive metadata list

- stylesheets/_component.choice.scss
- stylesheets/_component.forms.scss
- stylesheets/_component.range-slider.scss
- stylesheets/_component.select2.scss
- stylesheets/_component.toggle-switch.scss
- views/lexicon/forms.html.twig
- views/lexicon/forms/all.html.twig
- views/lexicon/index.html.twig
This improves the general obviousness of the user interface as well as improving keyboard navigation.
Also adds a new lexicon page with a sample of all form elements on.
(note alignment issues with checlbox/radios have been sorted since the gif was recorded)
> Improve visual presentation of focused form fields

- stylesheets/_component.forms.scss
All issues listed in #762 have been fixed:
> Fixed various radio/checkbox issues reported in 762

- stylesheets/_component.slider.scss
> Remove slider-container margin top on mobile

- js/NavMainComponent.js
Fixes an issue where secondary navigation would be closed when opening a second menu item.
> Fix issue causing secondary navigation to close when switching

- js/NavMainComponent.js
- stylesheets/_component.nav-list.scss
- stylesheets/_component.navigation.scss
* Attempts to fix the intermittent unresponsiveness of the more link
* Fixes issue causing more nav items to use incorrect typeface
---
There's an intermittent issue where the more link doesn't open the tertiary menu, I've not been able to pin down precise steps to replicate but adding preventDefault() on the method targeting the more link seems to work locally. Only time will tell whether it solves it in products.
This is an issue with products which add an ‘icon’ class to the nav-item, and cause FontAwesome to override Proxima Nova.
> Address 'more' navigation issues

- stylesheets/_component.navigation.scss
- stylesheets/_config.theme.scss
The navigation colors are defined directly in the component. I think they should be defined in `config.theme` so they can be more easily overridden.
**This is not an exhaustive list of what constitutes a breaking change**
| require changes to `main.js` | No |
| require changes to `index.js` | No |
| require changes to `pulsar.scss` | No |
| require changes to `gruntfile.js` | No |
| require changes to `package.json` (not including dev dependencies) | No |
| require changes to `base.html.twig` (or other core views like header/footer) | No |
| require new arguments to be passed to a js component | No |
| require markup changes to maintain functionality | No |
> Moved navigation color definitions in theme

- js/libs/modal.js
- tests/js/web/ModalTest.js
- views/lexicon/tabs/modals.html.twig
This change allows the modal to capture keyboard focus and permit keyboard navigation through embedded forms.
> When a dialog opens, focus moves to an element inside the dialog.
>
> _WAI-ARIA Authoring Practices / 3.8 Dialog (Modal) / Keyboard Interaction <sup>[[1](https://www.w3.org/TR/2017/NOTE-wai-aria-practices-1.1-20171214/#dialog_modal)]</sup>_
* Fields are not focused and cannot be navigated to by keyboard alone.
* `autofocus` HTML attribute has no effect in Bootstrap modals and cannot be used <sup>[[2](https://getbootstrap.com/docs/4.0/components/modal/#how-it-works)]</sup>
```
Given I have a modal with an input field that can be focused (except buttons)
When I open the modal
Then the field should be focused
```
I've started a new test file for any functionality we've added to …
> Focus first input field after opening a modal

- stylesheets/_component.input-groups.scss
- views/lexicon/forms/text.html.twig
> Stop multiple appended buttons from overlapping

- js/NavMainComponent.js
- tests/js/web/NavMainComponentTest.js
Fixes an issue where open popovers would appear over the secondary navigation when it was opened.
(Popovers still need to have a higher z-index than nav to stop them being obscured during normal operation)
> Close popovers when opening the secondary navigation

- stylesheets/_utility.states.scss
This restores the expected light red background to elements with the relevant state class.
I can’t find a legitimate reason for these to have been removed, their restoration may cause a few unexpected situations though…
**This change should not affect forms.** Form helpers have their own has-error styling, the top level `has-error`/`has-danger` classes explicitly avoid being applied to `form__group`.
`<tr class="has-error">...</tr>`
| require changes to `main.js` | ✅ No  |
| require changes to …
> Restore has-error / has-danger state classes

- stylesheets/_component.modals.scss
- stylesheets/_component.table-detail.scss
This PR doesn't break anything. Affects the titles in Standard, Full Screen Modal and Table Detail Pattern. Related issue #828 
**Expected results:**
Increased
Kept the same
Increased
> [828] Modal Titles and Table Details Pattern Title Font Size Increase

- stylesheets/_component.close.scss
- stylesheets/_component.modals.scss
Done to improve the accessibility and obviousness of the close control.
**Before**
**After**
Closes #815
> Increases contrast of ‘close’ control on modals

- docker-compose.yml
- docs/Local_development.md
- makefile
- provisioning/playbook.yml
Docker can be used instead of vagrant, which is much faster, start the server with `docker-compose up -d`.
Makefile has been updated with some things that were required for me to get a clean working install after reinstalling MacOS.
> Add docker config and update makefile to resolve recent installation issues

- docs/assets/code_examples/form_helpers/twig/radio-simple
- docs/assets/code_examples/form_helpers/twig/radio-simple-disabled
This is just a quick fix for the #699 . Docs have been properly updated.
> [699]Add missing ‘:’ in the Radio Simple Docs

- js/TableDetailComponent.js
- tests/js/web/TableDetailComponentTest.js
Related ticket: #809 
This PR adds the ability to close the Table Details from clicking on the backdrop overlay.
> [809] Close the table details panel when clicking outside of the details container

- stylesheets/_component.footer.scss
Increases contrast ratio to meet 1.4.3 Contrast (Minimum): (Level AA).
**Before:**
**After:**
Verified that aXe and SiteImprove no longer complain about contrast ratio.
> Increase contrast ratio of text in footer

- stylesheets/_structure.scaffolding.scss
- views/pulsar/layouts/base.html.twig
Required for Pulsar UIs to meet 2.4.1 Bypass Blocks: (Level A)
Skip link is hidden until `tab` key is pressed, a new wrapper element has been added to the base template around tab contents to act as the target.
> Add bypass block example

- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/media-presentation.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/media-presentation.html.twig
- views/lexicon/includes/notifications.html.twig
- views/pulsar/v2/helpers/html.html.twig
- views/pulsar/v2/helpers/nav.html.twig
This fix will stop Pulsar UIs from failing WCAG `1.1.1 Non-text Content: (Level A)`.
html.media helper will add `role="presentation"` if no `image_alt` attribute is supplied.
Also stopped notifications example using empty alt attributes but I believe this is implemented separately in continuum products.
> Stop using empty alt attributes on user guide and notifications menus

- views/pulsar/v2/helpers/nav.html.twig
Currently, SiteImprove raises errors with the main navigation links, this is particularly an issue in cases where multiple modules use the same link text (like 'settings').
**2.4.4 Link Purpose (In Context) Level A**
> The same link text is used for links going to different destinations. Users might not know the difference if they are not somehow explained.
>
> If the destination page is the same, this is not an issue.
>
>If the destination pages are not the same, make sure the links can be distinguished by their link texts or WAI-ARIA labels ('aria-labelledby' or 'aria-label') alone to make the difference clear to all users.
This PR changes our use of `aria-describedby` to `aria-labelledby`, which means that a settings link in the utilities menu would now be announced as "settings, …
> Improve labelling of main navigation links

- stylesheets/_component.datatables.scss
Fixes #870 
After changes in this branch:
**Long col header example**
**Long cell value**
**Responsive example**
> Fix no-wrap issues on collapsing datatables

- views/pulsar/v2/helpers/nav.html.twig
CMS uses labels with an embedded HTML comment, presumably for legacy ordering purposes.
```
Publishing
```
This value is passed to the heading as an `id`, and nav links as `aria-describedby`, but the HTML comment causes issues with automated accessibility testing tools (like SiteImprove) which flag it as a failure of **3.3.2 Labels or Instructions: (Level A)**.
This fix strips the comment, and also replaces spaces with hyphens to make sure the `XForms Pro` label doesn't break when turned into an `id`.
| require changes to `main.js` | No | …
> Make sure nav helper correctly parses CMS heading IDs

- stylesheets/_layout.tabs.scss
Adding a new wrapping div meant the descendant selector was no longer hiding tab panes.
> Restore tab functionality with the presence of the new bypass block markup

- stylesheets/_component.toggle-switch.scss
- stylesheets/_structure.forms.scss
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/toggle_switch-class.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/toggle_switch-error.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/toggle_switch-guidance-container.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/toggle_switch-guidance.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/toggle_switch-help.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/toggle_switch-label-hide.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/toggle_switch.html
- views/pulsar/v2/helpers/elem.html.twig
- views/pulsar/v2/helpers/form.html.twig
Previously there where a number of issues with toggle switches, these include:
- not being able to click the control label to activate the toggle
- an orphaned control label, not associated with a form control
This branch changes the the mark up of toggle switches fixing the above issues. The changes are backwards compatible so any existing toggle switches using raw mark up will be un effected though should be updated to use the `toggle_switch` helper or new mark up to address the above issues.
Browser tested in:
Screen reader tested in:
> Improved accessibility of toggle switches

- js/PulsarFormComponent.js
- tests/js/web/PulsarFormComponentTest.js
This PR is for date helpers without the placeholder option. It initializes the input field with the correct placeholder text to order accurately the letters of days, months and years.
Issue: #886
> [886] Add Placeholder Initialization Functionality for Date Helpers

- stylesheets/_component.buttons.scss
Example, `.table [href]` applies the consistent dotted link underline but we don’t particularly want them to leak to naked buttons at this time.
We will need to have a discussion about the a11y affordance of naked buttons, which will likely fail the scruitiny of a WCAG audit, but for now this hotfix is required to maintain existing visuals.
**Before**
**After**
> Stop default link underline from leaking to naked button styling

- stylesheets/_component.breadcrumb.scss
- stylesheets/_component.button-groups.scss
- stylesheets/_component.buttons.scss
- stylesheets/_component.close.scss
- stylesheets/_component.datatables.scss
- stylesheets/_component.flash.scss
- stylesheets/_component.forms.scss
- stylesheets/_component.navigation.scss
- stylesheets/_component.progress-lists.scss
- stylesheets/_component.range-slider.scss
- stylesheets/_component.search.scss
- stylesheets/_component.select2.scss
- stylesheets/_component.tab-help.scss
- stylesheets/_component.toggle-switch.scss
- stylesheets/_palette.base.scss
- stylesheets/_structure.scaffolding.scss
Focus styles have been improved to further meet 2.4.7 Focus Visible: (Level AA). 
Elements such as buttons, form elements, links, nav items, breadcrumbs and datatable sortable headers now show a orange outline when focused.
**Breadcrumbs:**
**Buttons:**
**Main nav:**
**Secondary nav:**
**Inputs:**
**Links:**
**Sortable datatable headers**
> Improved focus styles

- js/PulsarUIComponent.js
- tests/js/web/PulsarUIComponentTest.js
Defaults to 25, allows a custom page length to be set for a specific table, useful when embedding tables in modals where a shorter page length is required.
**Examples**
```
<table class="table datatable" data-page-length="10">...</table>
```
```
{{ 
html.datatable({
'data': tableData,
'data-page-length': '10'
})
}}
```
> Allow datatables to accept a custom pageLength

- stylesheets/_component.datatables.scss
Due to longstanding browser bugs in FireFox and Internet Explorer, using a background colour paints over the bottom border.
e.g. https://bugzilla.mozilla.org/show_bug.cgi?id=688556
This change uses background-clip to restore the expected border in FireFox and IE9+
**Before**
**After**
| require changes to `pulsar.scss` | ✅ No |
| require changes to `gruntfile.js` | ✅ No |
| require changes to `package.json` (not including dev dependencies) | ✅ No |
| require …
> Restore expected botton border to th cells in datatables

- js/libs/popover.js
Previously clicking a child of an element which has `data-toggle="popover"` did not trigger the popover as expected.
> Fix issue where children of elements triggering popovers do not trigger popovers

- views/lexicon/forms/dropzone.html.twig
- views/pulsar/v2/helpers/html.html.twig
`helperLabel`, `helperTitle`, `helperContent` and `helperContainer` have been replaced with the following valid data attributes `data-helper-label`, `data-helper-title`, `data-helper-content` and `data-helper-container`.
Fixes #939
> Fixes invalid dropzone attributes

- js/NavMainComponent.js
- tests/js/web/NavMainComponentTest.js
This change makes sure the quaternary navigation is closed when the more icon is clicked a second time.
The quaternary navigation stays open.
The quaternary navigation is closed.
Fixes #930 
| require changes to `pulsar.scss` | ✅ No |
| require changes to `gruntfile.js` | ✅ No |
| require changes to `package.json` (not including dev dependencies) | ✅ No |
| require changes to `base.html.twig` (or other core views like header/footer) | ✅ No |
| require new …
> Close quaternary menu when more icon is clicked a second time

- stylesheets/_component.tab-help.scss
- stylesheets/_structure.scaffolding.scss
Fixes issue reported in #951
UI can no longer be swiped to the left.
Original fix for search bar being obscured after jumping to a page fragment still works.
> Fix mobile swipe issue

- stylesheets/_component.forms.scss
Before:
After:
Line height is inherited from body is 24px which meets 1.4.12.
> Increased input help block font size to recommended 16px

- stylesheets/_component.forms.scss
- stylesheets/_component.input-groups.scss
- views/lexicon/forms.html.twig
- views/lexicon/forms/date.html.twig
- views/lexicon/forms/password.html.twig
- views/lexicon/forms/range.html.twig
- views/lexicon/forms/select.html.twig
- views/lexicon/forms/select2.html.twig
- views/lexicon/forms/text.html.twig
- views/lexicon/forms/time.html.twig
This change makes prepended/appended content hidden on overflow so that grid widths affect the total with of the input including any prepended/appended content. 
Change affects:
* form.date
* form.password
* form.range
* form.select
* form.select2
* form.text
* form.time
> Make pre/appended content be constrained by grid modifiers

- .gitattributes
Fixes a bug where locale files are not included in Pulsar bundle.
Closes #976
> Remove moment locale from .gitattributes

- js/DataTables/dataTablesDrawCallback.js
- js/DataTables/dataTablesInitComplete.js
- js/PulsarUIComponent.js
- stylesheets/_component.datatables.scss
- stylesheets/_component.pagination.scss
- tests/js/web/DataTables/dataTableDrawCallbackTest.js
- tests/js/web/DataTables/dataTablesInitCompleteTest.js
- tests/js/web/PulsarUIComponentTest.js
- views/lexicon/tabs/pagination.html.twig
This branch addresses a number of issues with the datatables pagination listed below:
1. Disabled links (such as "previous" on when on page 1) were shown to the user, could be focused and failed AA contrast. These have now been hidden both visually and from screen readers when not relevant. For example, there is no previous link when on page 1 and no next link when on the final page.
2. Link text was non descriptive to screen reader users. `aria-label`'s have now been added tp pagination links, for example `aria-label="page 1"` along with `aria-current="true"` where a link refers to the currently displayed page.
3. Pagination was shown when no records or only one page of records were present. Pagination is now only disabled when there are enough records to cause pagination.
4. For large …
> Datatables pagination a11y

- stylesheets/_component.table-detail.scss
- stylesheets/_component.tables.scss
- views/lexicon/patterns/table-detail/table-detail.html.twig
Fixes #995 
The issue seems to be related to a combination of the use of `display: table-cell` and `transform`. After trying multiple solutions and going down a lot of rabbit holes, I've set `display` to `none` on mobile when the panel is closed. This fixes the issue but loses the transition effect on mobile.
Tested in:
- Chrome
- Firefox
- Safari
- Edge
- IE11-9
- iOS Safari
After fix:
> Fix safari table-detail content shift issue

- js/area/signin/signin.js
- stylesheets/_component.dropzone.scss
- stylesheets/_component.loading.scss
- stylesheets/_component.navigation.scss
- stylesheets/_component.tab-help.scss
- stylesheets/_component.table-detail.scss
- stylesheets/_layout.tabs.scss
- stylesheets/_mixin.media-queries.scss
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/loading-label.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/loading-label.html.twig
- views/lexicon/tabs/loading.html.twig
- views/playground/login/index.html.twig
- views/pulsar/v2/helpers/html.html.twig
This MR adds support for OS prefer-reduced-motion settings to the following areas/components.
Fixes #1012 
1. Dropzone (icons are no longer animated on file drag and hover)
2. Loading component (now also supports a custom label for translations)
3. Navigation (All levels of navigation "fly outs")
4. Help mobile fly out
5. Table detail fly out
6. Continuum sign in video background playground
Any UIs using the animated galaxy background (typically continuum sign in) will need to remove the `data-vide-bg` data attribute and add `id="video-bg" data-video-bg="{path/to/galaxy.mp4}" data-video-poster="{path/to/galaxy.jpg}"`. See example below:
Change from:
`<div class="video" data-vide-bg="{path/to/galaxy.mp4}">`
to 
`<div class="video" id="video-bg" data-video-bg="{path/to/galaxy.mp4}" …
> 1012_add-reduced-motion-support

- stylesheets/_component.error-summary.scss
> Increase font weight of error summary

- README.md
Documentation was pointing to the old docs. This MR fixes the URL
There is still the notes for contributors link which still points to the old docs but i couldn't find the same page on the new docs
> Fix documentation link in Readme file

- js/ModulePermissionsComponent.js
- stylesheets/_component.forms.scss
CMS team reported an issue with the module page component, the following behaviour was not being correctly triggered:
```
Given I have a module with no sub-pages
When I select the main module checkbox
Then the CRUD controls should all be checked
```
**Before**
**After**
This change also restores indeterminate styling which was not originally added when we restyled the checkboxes.
> Fix issue causing modules with no pages to be incorrectly unselected

- js/Repeater/RepeaterComponent.js
- js/Repeater/RepeaterPlaceholderService.js
IE doesn't support `.remove()` so I've bumped the objects to jQuery objects so jQuery can do the `.remove()`.
Closes #1041
> Fix issue preventing IE11 from removing repeater placeholders

- js/FocusManagementService.js
- js/Repeater/RepeaterComponent.js
- js/Repeater/RepeaterPreviewService.js
- js/Repeater/repeaterComponentFactory.js
- js/utilities/UniqueIdService.js
- tests/js/web/FocusManagementServiceTest.js
- tests/js/web/Repeater/RepeaterComponentTest.js
- tests/js/web/Repeater/RepeaterPreviewServiceTest.js
- tests/js/web/utilities/UniqueIdServiceTest.js
- views/lexicon/forms/repeater.html.twig
- views/pulsar/v2/helpers/form.html.twig
This resolves various issues found in the repeater component, including:
1. Focus management for add, edit, save and close button actions
2. Changing add, save, cancel and edit buttons from links (`<a href="save">`) to `<button>`'s
3. Properly disabling the add button rather than just visually disabling it
4. Fixing issues where select2 child element IDs weren't unique after being cloned
5. Validation failures
6. Added a visually hidden caption to the repeater table
7. Adds actions column th text
Should be noted that SiteImprove still throws errors relating to hidden inputs not having a label. As their container has `display: none` this is not an issue and cannot be read by AT (confirmed in standard SRs).
Resolves #1071
> Repeater a11y fixes

- stylesheets/_component.choice.scss
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/choice-class.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/choice-disabled.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/choice-error.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/choice-guidance-container.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/choice-guidance.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/choice-help.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/choice-label-hide.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/choice-label.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/choice-multiple.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/choice-optimize-few.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/choice-required.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/choice.html
- views/pulsar/v2/helpers/elem.html.twig
- views/pulsar/v2/helpers/form.html.twig
This branch changes the behaviour of `form.choice()`. Previously when a `form.choice` helper, did not have the `many` option or contained 5 or less options the outputted radios/checkboxes were not grouped correctly (see #1077).
Previous mark up example:
```
<div class="form__group form-choice">
<label for="19" class="control__label">Choice checkbox</label>
<div class="controls">
<label class="control__label">
<input value="one" name="one" checked="" type="radio" class="form__control radio"> .   
<span class="form-choice__label">Checkbox One</span>
</label>
<label class="control__label">
<input value="two" name="one" type="radio" class="form__control radio">
<span class="form-choice__label">Checkbox Two</span>
</label>
<label class="control__label">
<input value="three" name="one" …
```
> form.choice improvements

- stylesheets/_component.rules.scss
- stylesheets/_utility.states.scss
Rule block headings and conditional links colours have been darkened to meet AA contrast.
Also removed generic state hover styles on `.has-error`, `has-warning` and `has-success` to prevent contrast failures of other components on hover.
Fixes #1085
> Bump rule heading and link styles to meet AA contrast

- stylesheets/_component.panels.scss
- views/lexicon/tabs/panels.html.twig
Reduce panel title size
Add a separator bar between title and content
Increase panel default padding
**Before**
**After**
> Give panels a face lift

- package-lock.json
- package.json
Pull in latest jaduSelectWoo (1.1.2) which resolves JQ3 deprecated event shorthand.
> Bump jaduSelectWoo to v1.1.2

- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/panel-no-title.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/panel-no-title.html.twig
- views/lexicon/tabs/panels.html.twig
- views/pulsar/v2/helpers/html.html.twig
This removes accessibility warnings when panels without titles are desired.
> If no title is passed to a panel, render as a div and remove the aria attribute

- js/PulsarUIComponent.js
This change removes the `valign` attribute from the empty table message on page load.
This issue has been raised on the [DataTables forum](https://datatables.net/forums/discussion/comment/145251/#Comment_145251) albeit a year ago, the only other solution for us would've been to for DataTables which isn't going to happen.
> Remove invalid valign attribute from DT empty message after load

- js/HelpTextComponent.js
- stylesheets/_component.tab-help.scss
This change fixes an odd IE11 issue where the sidebar help close button loses the child nodes when the viewport switches in and out of responsive mode.
Also added missing modern focus styles while I was here.
Closes #1120
> Fix issue where sidebar help close button loses child nodes in responsive mode

- js/PulsarFormComponent.js
I can’t see a way to control the generated colourpicker theme so while not ideal, this is a quick way to remove the inaccessible element after it has been created.
Addresses #1070
> Remove redundant, invalid text input when colour picker is created

- stylesheets/_component.datatables.scss
Add updated Pulsar select styles to the DataTables length dropdown.
**Regular**
**Responsive**
> Apply consistent select styling to datatable length dropdown

- js/DropdownButtonComponent.js
The notifications event target ends up being the icon, and it doesn’t use a btn__group therefore the previous `closest(Selectors.BTN_GROUP)` never hit it and the notifications list was closed immediately after opening.
This change also checks the closest `.dropdown` class to look for the open class, which seems to make all the toolbar dropdowns work again.
> fix issue where notifications dropdown wasn't visibly opening

- stylesheets/_component.tables.scss
This change removes the link border from links with button styling to keep both variants consistent.
**Before**
**After**
Closes #1117
> Switch off link border for button links within tables

- js/Tooltips/TooltipListener.js
- js/Tooltips/tooltipsFactory.js
- js/index.js
- js/main.js
- package-lock.json
- package.json
- stylesheets/pulsar.scss
- tests/js/web/Tooltips/TooltipListenerTest.js
- views/lexicon/index.html.twig
- views/lexicon/tabs/tooltips.html.twig
- views/lexicon/tabs/tooltips_v2.html.twig
This change adds a new WCAG 2.1 compliant Tooltip implementation. It uses the [Tippy.js](https://atomiks.github.io/tippyjs/) library with some custom configuration to address missing WCAG requirements. Existing tooltips are untouched.
- Tooltip content can be hovered
- Tooltip content is announced by screen reader when the triggering element is focussed
- Tooltips can be closed by pressing ESC
- By default, Tooltips display above the triggering element (can be changed via data attributes), though they will appear elsewhere (right, bottom, left) if there isn't space available (for example, if the element is at the top of the viewport or if there isn't space available on mobile).  
These new tooltips cover the requirements of [WCAG 2.1 …
> Accessible tooltips

- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/choice-required.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/edit_button-input.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/edit_button-link.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/edit_button-placements.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/edit_button-submit.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/edit_button-target.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/edit_button.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/media-actions.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/remove_button-link.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/remove_button-placements.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/remove_button-submit.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/remove_button-target.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/remove_button.html
- views/pulsar/v2/helpers/html.html.twig
- views/pulsar/v2/helpers/pulsar.html.twig
- views/pulsar/v2/helpers/rules.html.twig
- views/pulsar/v2/helpers/util.html.twig
This change updates the following helpers to use the new accessible tooltips:
* `html.edit_button`
* `html.remove_button`
* `util.required`
* rules (remove button and info icon)
Note: this is a straight swap, additional accessibility issues have been spotted and will be resolved in a separate MR.
> Update helper tooltips

- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/choice-required.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/status-placement.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/status-title.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/status-with-options.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/status-with-state.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/status.html
- views/pulsar/v2/helpers/html.html.twig
- views/pulsar/v2/helpers/util.html.twig
This fix resolves an issue where screen readers would announce the require indicator in input labels resulting in "star" being announced. For example: "First name star, required, edit text".
This fix resolves an issue where `html.status()` did not contain any screen reader readable text. `html.status()` now adds a SR friendly hidden span containing either the state text or any passed `title` option. This change also changes the helper over to the new accessible tooltips. Note that although tooltips on non-focusable element is normally avoided, in this case as the status mark up contains the same text in a SR friendly hidden span so the experience is the same for both sighted users and users of AT.
Changes have been tested in:
- Mac OS Voiceover
- JAWS 2018
- JAWS 18
- NVDA
> Fix SR issues with required indicator and status helper

- js/PulsarUIComponent.js
- stylesheets/_component.datatables.scss
- views/pulsar/v2/helpers/html.html.twig
Previously, when a collapsing datatable was in responsive mode and columns were hidden, the toggle control was an icon without SR friendly text. The parent `td` also had `tabindex="0"` to allow focus. This resulted in "blank" being read when the toggle control parent gained focus.
This change removed the `tabindex="0"` from the parent `td` and changes the icon to a button with hidden SR friendly text. This allows the toggle column control to be natively focussed and provides SR friendly hidden text which is announced as expected when SR users navigates the table or focusses the button.
Browser tested in:
- Chrome
- Firefox
- Safari
- Edge
- IE11
Screen reader tested in:
- MacOS VO
- JAWS 2018
- JAWS 18
- NVDA
Closes #1155
> Datatables column toggle improvements

- stylesheets/_component.flash.scss
- stylesheets/_component.ribbon.scss
- stylesheets/_component.toolbar.scss
- stylesheets/_layout.tabs.scss
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/status-placement.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/status-title.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/status-with-options.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/status-with-state.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/status.html
- views/pulsar/components/flash.html.twig
- views/pulsar/layouts/base.html.twig
- views/pulsar/v2/helpers/html.html.twig
Prior to the fixes in this change, flash messages were incorrectly positioned over the toolbar which hid other elements such as the search form and user dropdowns.
Position before fix:
Position after fix:
- Tweaked spacing between flash messages, main title and ribbon
- Change the mobile tab help container element from a `div` to `aside` to match the desktop version and prevent AXE warnings re content outside of landmarks
- Fixed broken mark up in `html.status` helper
- Change ribbon element from `aside` to a more appropriate `section`
> Fix flash message positioning and spacing improvements

- stylesheets/_component.breadcrumb.scss
- stylesheets/_palette.base.scss
Breadcrumbs:
Links:
Breadcrumbs:
Links:
Fixes #1163
> Improve link hover style

- stylesheets/_component.labels.scss
- stylesheets/_mixin.focus.scss
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/label-removable-states.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/label-removable.html
- views/pulsar/v2/helpers/html.html.twig
1. Labels within links now have appropriate focus styles:
2. Removable labels now use a `button` instead of a `a`.
3. Label remove button now reads "Remove {label text}" rather than just "Remove".
Fixes #1164
> html.label improvements

- stylesheets/_mixin.focus.scss
This change adds a visual focus indicator to the range input in addition to the existing thumb focus style.
After change:
Fixes #1173
> Fix range focus site improve error

- src/Jadu/Pulsar/Twig/Extension/AttributeParserExtension.php
- tests/unit/Jadu/Pulsar/Twig/Extension/AttributeParserExtensionTest.php
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/choice-required.html
- views/pulsar/v2/helpers/form.html.twig
Currently if a form helper is passed the `required` option, then both the `required` attribute and `aria-required="true"` is added to the outputted mark up. This no longer needed as most modern screen readers support the `required` attribute. It also creates a number of validation issues as seen in #1172 and #1175.
Tested in:
Mac VO (Safari)
Jaws 18 (IE11)
Jaws 2018 (IE11)
Jaws 2020 (ie11)
NVDA (IE11)
Fixes #1172 #1175
> Remove aria-required from form elements with the required attribute

- js/HelpTextComponent.js
- tests/js/web/HelpTextComponentTest.js
- views/pulsar/layouts/base.html.twig
This change fixes the AXE landmark errors reported in #1185. It also fixes an issue where a SR user could navigate to the mobile help container on desktop, which caused confusing screen reader results and also navigate to the closed help sidebar on mobile resulting in a blank screen.
Fixes #1185
> Fix landmark and SR issues with mobile help side bar

- js/DisableUiComponent.js
- js/PulsarUIComponent.js
- stylesheets/_component.forms.scss
- stylesheets/_utility.utilities.scss
- tests/js/web/DisableUiComponentTest.js
- tests/js/web/PulsarUIComponentTest.js
- views/lexicon/patterns/disabled-ui/disabled-ui.html.twig
Using opacity instead of a lighter `color` achieves the same visual effect, keeps a11y tools happy, and meets WCAG exceptions for disabled element contrast.
Also uses opacity for disabled choice labels
**Before**
Using `color: color(text, disabled);` (`#bebebe`)
**After**
This uses `opacity: .4;`, a touch darker than before, but still enough, I feel.
Closes #1177
> Add aria-disabled attribute to disabled UI wrapper and change text color for disabled links

- js/Repeater/RepeaterDataService.js
- tests/js/web/Repeater/RepeaterDataServiceTest.js
This change fixes the issues reported in #1174 by adding `display: none` to the saved data hidden fields (via `.u-display-none`).
Fixes #1174
> Fix SI error by properly hiding hidden fields

- stylesheets/_component.panels.scss
- stylesheets/_component.timeline.scss
- views/lexicon/tabs/panels.html.twig
This changes fixes the issues reported in #1166 namely colour contrast failures for success and danger panel CTA button text colour.
I've also resolved some lexicon specific a11y errors relating to duplicate landmark names, incorrectly formatted date time attribute values and timeline avatar colour contrast.
Fixes #1166
> Fixed panel cta contrast issue and related lexicon a11y tool errors

- stylesheets/_component.choice.scss
- stylesheets/_component.forms.scss
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/button_group-error.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/button_group-guidance-container.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/button_group-guidance.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/button_group-help.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/button_group-label-hide.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/button_group-label.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/button_group-type_button.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/button_group-type_checkbox.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/button_group-type_radio.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/button_group.html
- views/pulsar/v2/helpers/form.html.twig
This PR changes the mark up used in `form.button_group` from `div` and `label` to `fieldset` and `legend`. It also replaces the more specific fieldset styling for `form-choice` and `form__group--compound` with something more flexible and generic.
Browser tested in:
- Safari
- Chrome
- Firefox
- Edge
- IE11
- iOS safari
Fixes #1168
> form.button_group a11y fixes

- stylesheets/_component.button-groups.scss
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/button_group-disable-all.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/button_group-disable-all.html.twig
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/button_group-disable-single.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/button_group-disable-single.html.twig
- views/lexicon/forms.html.twig
- views/pulsar/v2/helpers/form.html.twig
This change allows button groups using the nested syntax (that pass an options array instead of passing full helpers as `items`) to either disable individual buttons, or all buttons.
Pass `disabled` on the parent element to disable all children:
```twig
{{
form.button_group({
'label': 'Button group',
'disabled': true,
'items': [
{
'id': 'foo1',
'label': 'Foo',
'name': 'foo-1',
'checked': true
},
{
'id': 'bar1',
'label': 'Bar',
'name': 'foo-1'
},
{
'id': 'baz1',
'label': 'Baz',
'name': 'foo-1'
}
]
})
}}
```
Pass `disabled` on a child in the `items` array to disable that button:
```twig
{{
form.button_group({
'label': 'Button group',
'items': [
{
'id': 'foo1',
'label': 'Foo',
'name': 'foo-1',
'checked': true
},
{
'id': 'bar1',
'label': 'Bar',
'name': 'foo-1',
'disabled': true,
},
{
'id': …
```
> Improve options for disabling button group buttons

- js/TableDetailComponent.js
- tests/js/web/TableDetailComponentTest.js
- views/lexicon/patterns/table-detail/index.html.twig
- views/lexicon/patterns/table-detail/table-detail-collapsing.html.twig
This change tweaks the event handlers to cope with the detail trigger changing DOM position, and adds a check so that the detail content can be fetched from the expected row rather than the collapsed detail.
Also adds a lexicon example for collapsing tables to the table detail pattern, and a new `aria-labelledby` attribute to bring in the accessibility improvements from modals requested by #820.
Closes #819
Closes #820
| Does this pull request... | ⚠️ Yes / ✅ No |
| require changes to `pulsar.scss` …
> Make table detail triggers work with DT collapse mode

- js/HelpTextComponent.js
- stylesheets/_component.tab-help.scss
- tests/js/web/HelpTextComponentTest.js
This moves the mobile help toggle from being a child of the .main-title element, to being a child of the parent .toolbar which has a significantly higher chance of being always available in the layout.
Closes #821
| Does this pull request... | ⚠️ Yes / ✅ No |
| require changes to `pulsar.scss` | ✅ No |
| require changes to `gruntfile.js` | ✅ No |
| require changes to `package.json` (not including dev dependencies) | ✅ No |
| require changes to `base.html.twig` (or other core views like …
> Allow mobile help button to still be present if no main title is available

- views/lexicon/tabs/modals.html.twig
> Add missing a11y improvements to modal examples in Lexicon

- package-lock.json
- package.json
Due to issues building JS related to other versions of timepicker, I'm going to temp lock to v1.13.2 until a better fix can be investigated.
> Lock Timepicker to 1.13.2

- js/DataTables/dataTablesDrawCallback.js
- js/DataTables/dataTablesInitComplete.js
- js/PulsarUIComponent.js
- tests/js/web/DataTables/dataTablesDrawCallbackTest.js
- tests/js/web/DataTables/dataTablesInitCompleteTest.js
- views/lexicon/tables/basic-scrolling.html.twig
- views/lexicon/tables/basic.html.twig
- views/lexicon/tables/datatable-collapse.html.twig
- views/lexicon/tables/datatable-empty.html.twig
- views/lexicon/tables/datatable.html.twig
- views/lexicon/tables/sortable.html.twig
- views/pulsar/v2/helpers/html.html.twig
This PR resolves the following issues found while a11y auditing lexicon datatables examples:
1. Scrollable/overflowing tables incorrectly displayed the overflow gradient styles on load when no overflow was present
2. Table pagination nav landmark was present in the DOM when there were no pagination links, resulting in SR users being able to jump/nagivate to the empty navigation
3. Pagination links were read as "group" in SRs. They now announce as Buttons
4. Collapsed row toggle button label wasn't clear (read as if it would expand all collapsed columns for the table)
5. `html.datatable` helper did not allow for table captions
6. Added table captions to lexicon examples
7. Scrollable code examples in lexicon sidebar where not keyboard accessible
TODO: documentation change to highlight new …
> Datatables accessibility improvements

- js/HelpTextComponent.js
- tests/js/web/HelpTextComponentTest.js
This fixes an issue where links/buttons within the mobile help sidebar could be tabbed to and be seen/navigated to by screen readers.
Fixes #1247
> Ensure interactive elements in closed mobile sidebar cannot be focussed or seen by SRs

- stylesheets/_component.forms.scss
- stylesheets/_structure.grid.scss
Chose to add a grid mixin for this as we're already doing a calculation for the control label, so this width calculation will obey the configured values for gutters and columns.
**Before**
(Vertical line here is an xScope guide, not a border visible in the UI)
**After**
Closes #1242
> Make indented fields adjust their total width by subtracting the label width

- stylesheets/_layout.settings.scss
- views/playground/branding/branding.html.twig
- views/playground/branding/index.html.twig
This change: 
* increases the height of the select element to match the expected height of buttons
* moves the caret position to match the new height (I could've calculated this based on the button padding vars but it didn't feel right using them here)
* adds additional padding on the right of the select element to improve how page numbers look (we don't have extra padding on the selects so we can sensibly cope with long options at narrow grid widths, but here it's always page numbers so is desired)
* adds support for the select label as provided in the original issue ticket.
**Before**
**After**
Closes #1246
> Improve alignment of page selections with settings UI

- stylesheets/_component.navigation.scss
**Before**
**After**
This does reduce the visual area of the hovered item by a few px but the clickable hit target remains the same.
Closes #1236
> Stop focused nav items being obscured by hovered items

- stylesheets/_structure.forms.scss
The code comment related to this was:
```// take into account any textarea border which might look like it’s overlapping at 100% width```
Suspect this was a holdout from an older version of Pulsar which used thicker borders on input elements, maybe combined with older IE versions with larger scrollbars... either way, I can't see a legit reason for this to exist anymore.
Closes #1229
> Remove 99% width constraint from textareas

- stylesheets/_component.notifications.scss
- stylesheets/_component.remove-button.scss
* Increase default contrast to meet AA
* Add missing focus styles
* Tweak position to cope with new button padding added to accommodate focus styles
**After (focused and non-focused)**
Closes #1250
> Improve contrast of notifications dismiss button

- views/lexicon/forms/dropzone.html.twig
- views/lexicon/tabs/popovers.html.twig
- views/pulsar/v2/helpers/html.html.twig
As popover are due to be deprecated, this branch removes the popover found in the dropzone file uploader and replaces with plain text.
> Removed dropzone popover

- stylesheets/_component.modals.scss
- views/lexicon/tabs/modals.html.twig
This branch fixes the below markup issues found on the lexicon examples:
1. The modal X close button incorrectly had `aria-hidden="true"` and was missing an `aria-label`. `aria-label="Close modal dialog"` has been added to the button and the X wrapped in `<span aria-hidden="true">.
2. The full page modal used a link for the close button, this has been changed to a button and related styles added.
3. Full page modal example, incorrectly had `aria-hidden="true"` on the main `.modal` wrapper and was missing `aria-modal="true"`
4. The 2 modal example which were shown on page load have been hidden to prevent SR testing issues.
5. Redundant `fade` classes have been removed.
Documentation update to follow.
> Resolve modal markup issues

- js/PulsarFormComponent.js
This was previously reserved for buttons only.
`data-target` will take priority over `href`
Closes #1266
> Allow a modal link to use the data-target attribute

- js/Modals/ModalFocusService.js
- tests/js/web/Modals/ModalFocusServiceTest.js
- views/lexicon/tabs/modals.html.twig
This branch fixes #1280 
**New behaviour**
When a modal is opened focus is set on:
- The first focusable element, regardless of presence of a `form`
- The close X button in the modal header, if there are no focusable elements in the modal body
- The `Cancel` button in the modal footer, if there are no focusable elements in the modal body and there is no close X button in the modal header.
> Fix modal focus issues

- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/actions_menu-dividers.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/actions_menu-items.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/html/actions_menu.html
- views/pulsar/v2/helpers/html.html.twig
This branch removes the hardcoded `actions_menu` ID from the actions menu drop down button generated by the `html.actions_menu` helper.
This was causing "multiple elements with same ID" failures In JS tabs, when multiple tabs had an actions menu dropdown button.
Couldn't find any references to this ID in JS in CXM, CMS or XFP.
> Remove hardcoded actions menu ID causing dup ID validation failures in JS tabs

- package-lock.json
- package.json
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/select2-placeholder-multiple.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/select2-placeholder-multiple.html.twig
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/select2-placeholder-single.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/select2-placeholder-single.html.twig
- views/lexicon/forms/select2.html.twig
- views/pulsar/v2/helpers/elem.html.twig
This pull request contains the following changes:
- Jadu/selectWoo updated to latest version (jadu-1.1.3). This fixes a number of a11y tool errors and improves screen reader coverage
- Select2 twig helper no longer incorrectly adds the `placeholder` attribute to native selects causing markup validation failures
- Select2 twig helper now adds the empty `<option value="">{placeholder}</option>` required for single select select2's when the `placeholder` option is used
TODO: Will be updating documentation to add `placeholder` option examples after merge.
> Select woo jadu 1.1.3

- js/FilterBarComponent.js
- js/HelpTextComponent.js
- js/PulsarFormComponent.js
- js/TabEnhancements/TabEnhancements.js
- js/index.js
- js/libs/tab.js
- js/main.js
- tests/js/web/FilterBarComponentTest.js
- tests/js/web/PulsarFormComponentTest.js
- tests/js/web/TabEnhancements/TabEnhancementsTest.js
- views/lexicon/patterns/filters/create-filter.html.twig
- views/lexicon/patterns/filters/load-filter.html.twig
This branch contains the following changes:
1. Fixed an issue where select2's in the filter bar that had a placeholder would be displayed on page load (see below)
2. Also fixed an issue where filterbar select2's with multiple selections would be displayed incorrectly - "label:Option1Option2" , rather than "label: Option1, Option2".
#1258 introduced an issue where event handlers and JS would break on tab change. This resulted in the following elements being broken (after a js tab change): 
- select2
- colour picker
- date picker
- time picker
- repeater
- choice block radios and checkboxes
- dropzone
- jstree
This branch fixes the above issues and moves `tab.js` enhancements to their own class with relevant tests. As this functionality is not included in `tab.js`, the new `TabEnhancements` …
> Filterbar select2 placeholder and tab.js fixes

- views/lexicon/tabs/modals.html.twig
Added lexicon example to test modal focus management when error summary in use:
> Add lexicon example of modal with error summary

- stylesheets/_utility.states.scss
Related to Jira issue XFP-4339, this change uses `color(link, dark)` when a link is inside a container using the common state classes. Not entirely obvious using screenshots, but following use cases pass measurement.
May need to be cherry-picked into beta2 if one is requested.
> Ensure AA contrast of links within state containers

- stylesheets/_palette.base.scss
To be merged into `CMS/flatcap-july` and included into products when CMS request `beta2`
> Darken help text to fix contrast warning in IBM a11y tool

- stylesheets/_component.forms.scss
Fixes a AA issue reported in CMS, where validation states within a table__form container don't meet contrast.
**Before**
**After**
To be included in `11.0.0beta2`
> Ensure AA contrast for help/warning states within table forms

- stylesheets/_component.piano.scss
Related to CMS-6986
This rule causes the scrollbar to not be visible, the git history says that it was added to resolve an issue with full screen tables in the Perceptive Content integrations UI.
I’ve tested this UI with and without this ruleset active, in the usual browsers, and there is no negative effect with removing it, the presumption at this time is that there have been other changes to either Pianos or Tables which render this changeset redundant.
> Make sure horizontal scrollbar is visible for tabbed navigation inside piano content

- stylesheets/_component.cards.scss
Requiring cards to use a h3 means we might be using inappropriate heading levels. This change also allows non `h*` tags to be used.
**Before**
**After**
> Set a consistent font size for card titles so that any heading tag can be used

- stylesheets/_component.tables.scss
Flush inputs are being affected by the `nowrap` rule which forces tables to maintain horizontal width and rely on scrolling. This change allows flush inputs to wrap and put the input on the left edge as expected.
**Example**
> Stop flush inputs inheriting nowrap from horizontal table cells

- stylesheets/_component.forms.scss
- stylesheets/_component.tables.scss
Previous solve for this didn’t fix all instances, changing the background (as previously suggested) should fix all contrast state issues.
> Lighten table form backgrounds to fix error contrast

- stylesheets/_component.forms.scss
This stops the `nowrap` in horizontal tables from affecting help blocks.
**Before**
**After**
> Make sure help blocks wrap properly when in a table—horizontal form

- stylesheets/_component.status.scss
- stylesheets/_palette.base.scss
No visual difference, but makes sure danger contrast meets AA when on a background of `#fafafa`
Relates to XFP-4364
> Fix contrast issue when danger text/icon colour appears in a table row with hover effect

- CHANGELOG.md
- js/libs/tooltip.js
There is a low chance of this being exploited as it would need code access to change the options of the tooltip init code.
2 fixed alerts
Unsafe jQuery plugin (js/libs/tooltip.js#L53)
Unsafe jQuery plugin (js/libs/tooltip.js#L162)
> Patch areas in tooltip code where malicious selectors could be passed through tooltip options

- CHANGELOG.md
- stylesheets/_structure.forms.scss
Adds a `.form__group--tight` modifier to reduce the vertical margins of a form group to allow related controls to be brought closer together.
This change is required to address a scratch rule currently in use in XFP.
**Before**
**After**
Closes #711
> Add tight spacing option for form groups

- CHANGELOG.md
- stylesheets/_component.tables.scss
- views/lexicon/tables/basic.html.twig
This branch adds basic styling to table `<caption>` elements.
Before (chrome default styling):
After:
Fixes #1347
> Table caption styling

- CHANGELOG.md
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/button_group-error.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/checkbox-error.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/choice-error.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/content-error.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/date-error.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/error-multiple.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/error-single.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/file-error.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/password-error.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/radio-error.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/radio_inline-error.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/select-error.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/select2-error.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/text-error.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/textarea-error.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/time-error.html
- tests/unit/Jadu/Pulsar/Twig/Macro/Fixtures/form/toggle_switch-error.html
- views/pulsar/v2/helpers/form.html.twig
This branch adds  a visually hidden but accessible`<span class="hide">Error: </span>` to helper outputted form error text.
This improves SR experience making it more obvious to SR users when a field has an error. Inspired by the GDS error message pattern.
There is no visual difference in error text.
Tested in JAWS, NVDA and Voiceover.
Fixes #1348
> Prepend form error text with visually hidden “Error:”

- stylesheets/_component.forms.scss
Add focus styling for CK editor (previously scratched in XFP) with a few small tweaks to make it consistent with other input focus styles. Tested in CXM.
Fixes #1365
> Added CK editor focus styles

- js/area/signin/signin.js
- stylesheets/_component.datatables.scss
- stylesheets/_component.modals.scss
- stylesheets/_component.signin.scss
- views/playground/login/index.html.twig
Previously, a lot of branding related overrides were held in Connect's pre-authorisation view, these have been significantly streamlined so the signin.scss file can make more use of inheritance. Other changes include:
Long organisation names now break-word instead of break-all, avoiding situations where a single word is split onto two lines.
Danger panel presentation improved, they should now 
- Span the width of the container
- Have a red danger background colour
- Have white text, and a white exclamation icon
- Have white top and bottom border to visually separate it from dark background colours
When viewing on a mobile device, or narrow viewport, the sign in UI is now centered instead of being left-aligned. 
At very narrow widths, the sign in UI will also close the gap at the top of …
> Improvements to sign-in screens following Connect integration

- stylesheets/_component.forms.scss
I believe this rule was introduced when addressing styling issues for the Sign In UIs, especially for Jadu Connect and had the unintended consequence of negatively affecting Rules as demonstrated below.
Removing doesn't seem to have a negative effect on Sign In anymore, tested using the sign in testbed (private Jadu repo).
Before:
After:
> Restore expected field widths on form components in rules UI

- views/lexicon/patterns/tab-header/table.html.twig
- views/lexicon/tabs/checkgrid.html.twig
- views/playground/admin-mappings/index.html.twig
- views/playground/branding/branding.html.twig
- views/playground/galaxies/admins.html.twig
- views/playground/galaxies/designer.html.twig
- views/playground/galaxies/security.html.twig
- views/playground/galaxies/settings.html.twig
- views/playground/galaxies/sites.html.twig
- views/playground/galaxies/theme.html.twig
- views/playground/rebooking/index.html.twig
- views/playground/slider/index.html.twig
- views/playground/sortable/tab.html.twig
- views/playground/xfp-received/index.html.twig
- views/playground/xfp-received/log.html.twig
- views/playground/xfp-received/tab.html.twig
- views/pulsar/components/toolbar.html.twig
- views/pulsar/layouts/pulsar.html.twig
It's a recent requirement (how recent I don't actually know) to explicitly define macros you're using in a child template even if they're defined in a parent template. This PR adds them where they're missing.
> Explicitly set html variable where it is used

- stylesheets/_component.cards.scss
- stylesheets/_component.lists.scss
* Modifies padding of card blocks to cater for the increased height now that months are included
* Ensure the definition list grid spans the available width
> Fix layout issues on recurring bookings UI

- js/DropZone/DropZone.js
The exact same bug fixed in https://github.com/jadu/pulsar/pull/1556 can still occur if you use the drag-and-drop feature instead of just selecting to browse files. We need to replicate the change for drag and dropped attachments.
> Qu 4501 (round two)

- js/DropZone/DropZone.js
Input nodes may not always be immediately available if the elements load at a later time (_like in a modal)_ or are otherwise manipulated.
> Add null check for missing input node ids
